# -*- coding: utf-8 -*-
'''
Created on 10 jul. 2024

@author: Raymond
'''
networks = [
"+globosat",
"1+1",
"10 bold",
"10.bold",
"10_bold",
"10-bold",
"10b",
"10 peach",
"10.peach",
"10_peach",
"10-peach",
"10p",
"13th street",
"13th.street",
"13th_street",
"13th-street",
"13s",
"13ème rue",
"13ème.rue",
"13ème_rue",
"13ème-rue",
"13r",
"2be",
"2×2",
"3net",
"3sat",
"5star",
"6'eren",
"6play",
"6ter",
"7 rm spain",
"7.rm.spain",
"7_rm_spain",
"7-rm-spain",
"7rs",
"7mate",
"8tv",
"a haber",
"a.haber",
"a_haber",
"a-haber",
"a&e",
"aag tv",
"aag.tv",
"aag_tv",
"aag-tv",
"ab1",
"abc (au)",
"abc",
"abc.(au)",
"abc_(au)",
"abc-(au)",
"abc (ja)",
"abc.(ja)",
"abc_(ja)",
"abc-(ja)",
"abc (ph)",
"abc.(ph)",
"abc_(ph)",
"abc-(ph)",
"abc (us)",
"abc.(us)",
"abc_(us)",
"abc-(us)",
"abc comedy",
"abc.comedy",
"abc_comedy",
"abc-comedy",
"abc family",
"abc.family",
"abc_family",
"abc-family",
"abc kids",
"abc.kids",
"abc_kids",
"abc-kids",
"abc me",
"abc.me",
"abc_me",
"abc-me",
"abc news 24",
"abc.news.24",
"abc_news_24",
"abc-news-24",
"an24",
"abc iview",
"abc.iview",
"abc_iview",
"abc-iview",
"abc1",
"abc2",
"abc3",
"abs cbn broadcasting company",
"abs.cbn.broadcasting.company",
"abs_cbn_broadcasting_company",
"abs-cbn-broadcasting-company",
"acbc",
"ahc",
"allblk",
"alt balaji",
"alt.balaji",
"alt_balaji",
"alt-balaji",
"amc+",
"amc",
"ant1",
"aol",
"aptn",
"art tv",
"art.tv",
"art_tv",
"art-tv",
"artv",
"ary digital",
"ary.digital",
"ary_digital",
"ary-digital",
"ary one world",
"ary.one.world",
"ary_one_world",
"ary-one-world",
"aow",
"ary shopping channel",
"ary.shopping.channel",
"ary_shopping_channel",
"ary-shopping-channel",
"asc",
"ary zouq",
"ary.zouq",
"ary_zouq",
"ary-zouq",
"at x",
"at.x",
"at_x",
"at-x",
"atn aastha channel",
"atn.aastha.channel",
"atn_aastha_channel",
"atn-aastha-channel",
"aac",
"atresplayer premium",
"atresplayer.premium",
"atresplayer_premium",
"atresplayer-premium",
"atv (at)",
"atv",
"atv.(at)",
"atv_(at)",
"atv-(at)",
"atv (be)",
"atv.(be)",
"atv_(be)",
"atv-(be)",
"atv (hk)",
"atv.(hk)",
"atv_(hk)",
"atv-(hk)",
"atv (tr)",
"atv.(tr)",
"atv_(tr)",
"atv-(tr)",
"avro",
"avrotros",
"axn españa",
"axn.españa",
"axn_españa",
"axn-españa",
"axn polska",
"axn.polska",
"axn_polska",
"axn-polska",
"axn",
"axs tv",
"axs.tv",
"axs_tv",
"axs-tv",
"aaj tv",
"aaj.tv",
"aaj_tv",
"aaj-tv",
"abema tv",
"abema.tv",
"abema_tv",
"abema-tv",
"abu dhabi tv",
"abu.dhabi.tv",
"abu_dhabi_tv",
"abu-dhabi-tv",
"adt",
"acorn tv",
"acorn.tv",
"acorn_tv",
"acorn-tv",
"action",
"adult channel",
"adult.channel",
"adult_channel",
"adult-channel",
"adult swim (fr)",
"adult swim",
"adultswim",
"adult.swim.(fr)",
"adult_swim_(fr)",
"adult-swim-(fr)",
"asf",
"adult.swim",
"adult_swim",
"adult-swim",
"africa magic",
"africa.magic",
"africa_magic",
"africa-magic",
"aftenposten",
"aizo tv",
"aizo.tv",
"aizo_tv",
"aizo-tv",
"al alam",
"al.alam",
"al_alam",
"al-alam",
"al aoula",
"al.aoula",
"al_aoula",
"al-aoula",
"al arabiyya",
"al.arabiyya",
"al_arabiyya",
"al-arabiyya",
"al badeel",
"al.badeel",
"al_badeel",
"al-badeel",
"al hidaya al libiya",
"al.hidaya.al.libiya",
"al_hidaya_al_libiya",
"al-hidaya-al-libiya",
"ahal",
"al jadeed",
"al.jadeed",
"al_jadeed",
"al-jadeed",
"al jamahiriya tv english",
"al.jamahiriya.tv.english",
"al_jamahiriya_tv_english",
"al-jamahiriya-tv-english",
"ajte",
"al jazeera america",
"al.jazeera.america",
"al_jazeera_america",
"al-jazeera-america",
"aja",
"al jazeera",
"al.jazeera",
"al_jazeera",
"al-jazeera",
"al libiya",
"al.libiya",
"al_libiya",
"al-libiya",
"al mayadeen",
"al.mayadeen",
"al_mayadeen",
"al-mayadeen",
"al mounawaa",
"al.mounawaa",
"al_mounawaa",
"al-mounawaa",
"al nahar",
"al.nahar",
"al_nahar",
"al-nahar",
"al shababiyah",
"al.shababiyah",
"al_shababiyah",
"al-shababiyah",
"al jamahiriya tv",
"al.jamahiriya.tv",
"al_jamahiriya_tv",
"al-jamahiriya-tv",
"ajt",
"al madina tv",
"al.madina.tv",
"al_madina_tv",
"al-madina-tv",
"amt",
"alibi",
"all 4",
"all.4",
"all_4",
"all-4",
"allociné",
"alnabaa",
"alpha tv gujarati",
"alpha.tv.gujarati",
"alpha_tv_gujarati",
"alpha-tv-gujarati",
"atg",
"alpha tv punjabi",
"alpha.tv.punjabi",
"alpha_tv_punjabi",
"alpha-tv-punjabi",
"atp",
"alpha tv",
"alpha.tv",
"alpha_tv",
"alpha-tv",
"altice studio",
"altice.studio",
"altice_studio",
"altice-studio",
"amazon freevee",
"amazon.freevee",
"amazon_freevee",
"amazon-freevee",
"amazon prime video",
"amazon.prime.video",
"amazon_prime_video",
"amazon-prime-video",
"apv",
"america one television network",
"america.one.television.network",
"america_one_television_network",
"america-one-television-network",
"aotn",
"amman tv",
"amman.tv",
"amman_tv",
"amman-tv",
"américa tv",
"américa.tv",
"américa_tv",
"américa-tv",
"and tv",
"and.tv",
"and_tv",
"and-tv",
"anhui tv",
"anhui.tv",
"anhui_tv",
"anhui-tv",
"animal planet",
"animal.planet",
"animal_planet",
"animal-planet",
"animax",
"anime hodai",
"anime.hodai",
"anime_hodai",
"anime-hodai",
"anime network",
"anime.network",
"anime_network",
"anime-network",
"anime oav",
"anime.oav",
"anime_oav",
"anime-oav",
"antena 1",
"antena.1",
"antena_1",
"antena-1",
"antena 3",
"antena.3",
"antena_3",
"antena-3",
"antenne 2",
"antenne.2",
"antenne_2",
"antenne-2",
"apple music",
"apple.music",
"apple_music",
"apple-music",
"apple tv+",
"apple.tv+",
"apple_tv+",
"apple-tv+",
"arena",
"arirang tv",
"arirang.tv",
"arirang_tv",
"arirang-tv",
"arte creative",
"arte.creative",
"arte_creative",
"arte-creative",
"arte1",
"arte",
"astro awani",
"astro.awani",
"astro_awani",
"astro-awani",
"astro citra",
"astro.citra",
"astro_citra",
"astro-citra",
"astro oasis",
"astro.oasis",
"astro_oasis",
"astro-oasis",
"astro prima",
"astro.prima",
"astro_prima",
"astro-prima",
"astro ria",
"astro.ria",
"astro_ria",
"astro-ria",
"astro warna",
"astro.warna",
"astro_warna",
"astro-warna",
"atomfilms",
"audience network",
"audience.network",
"audience_network",
"audience-network",
"audience",
"australian christian channel",
"australian.christian.channel",
"australian_christian_channel",
"australian-christian-channel",
"acc",
"b4u movies",
"b4u.movies",
"b4u_movies",
"b4u-movies",
"b4m",
"b4u music",
"b4u.music",
"b4u_music",
"b4u-music",
"b92",
"bbangya tv",
"bbangya.tv",
"bbangya_tv",
"bbangya-tv",
"bbc alba",
"bbc.alba",
"bbc_alba",
"bbc-alba",
"bbc america",
"bbc.america",
"bbc_america",
"bbc-america",
"bbc four",
"bbc.four",
"bbc_four",
"bbc-four",
"bbc hd",
"bbc.hd",
"bbc_hd",
"bbc-hd",
"bbc kids",
"bbc.kids",
"bbc_kids",
"bbc-kids",
"bbc music",
"bbc.music",
"bbc_music",
"bbc-music",
"bbc news",
"bbc.news",
"bbc_news",
"bbc-news",
"bbc northern ireland",
"bbc.northern.ireland",
"bbc_northern_ireland",
"bbc-northern-ireland",
"bni",
"bbc one",
"bbc.one",
"bbc_one",
"bbc-one",
"bbc parliament",
"bbc.parliament",
"bbc_parliament",
"bbc-parliament",
"bbc scotland",
"bbc.scotland",
"bbc_scotland",
"bbc-scotland",
"bbc three",
"bbc.three",
"bbc_three",
"bbc-three",
"bbc two",
"bbc.two",
"bbc_two",
"bbc-two",
"bbc uktv (au)",
"bbc uktv",
"bbcuktv",
"bbc.uktv.(au)",
"bbc_uktv_(au)",
"bbc-uktv-(au)",
"bua",
"bbc wales",
"bbc.wales",
"bbc_wales",
"bbc-wales",
"bbc world news",
"bbc.world.news",
"bbc_world_news",
"bbc-world-news",
"bwn",
"bbc iplayer",
"bbc.iplayer",
"bbc_iplayer",
"bbc-iplayer",
"bbc",
"bet+",
"bet",
"bfm tv",
"bfm.tv",
"bfm_tv",
"bfm-tv",
"bnn (nl)",
"bnn",
"bnn.(nl)",
"bnn_(nl)",
"bnn-(nl)",
"bnnvara",
"bnt1",
"br alpha",
"br.alpha",
"br_alpha",
"br-alpha",
"brtn tv2",
"brtn.tv2",
"brtn_tv2",
"brtn-tv2",
"bs11",
"byutv",
"babyfirsttv",
"babytv",
"baiskoafu",
"bandai channel",
"bandai.channel",
"bandai_channel",
"bandai-channel",
"betv",
"betevé",
"beyaz tv",
"beyaz.tv",
"beyaz_tv",
"beyaz-tv",
"big ten network (btn)",
"big ten network",
"bigtennetwork",
"big.ten.network.(btn)",
"big_ten_network_(btn)",
"big-ten-network-(btn)",
"btnb",
"bilibili",
"bio",
"blackpills",
"blaze",
"blim",
"blip",
"bloomberg television",
"bloomberg.television",
"bloomberg_television",
"bloomberg-television",
"blutv",
"blue sky (greece)",
"blue sky",
"bluesky",
"blue.sky.(greece)",
"blue_sky_(greece)",
"blue-sky-(greece)",
"bsg",
"boomerang",
"bounce tv",
"bounce.tv",
"bounce_tv",
"bounce-tv",
"bravo (nz)",
"bravo",
"bravo.(nz)",
"bravo_(nz)",
"bravo-(nz)",
"bravo (uk)",
"bravo.(uk)",
"bravo_(uk)",
"bravo-(uk)",
"britbox",
"brutx",
"bubble hits",
"bubble.hits",
"bubble_hits",
"bubble-hits",
"c more",
"c.more",
"c_more",
"c-more",
"c span",
"c.span",
"c_span",
"c-span",
"c31",
"cbbc",
"cbc (eg)",
"cbc",
"cbc.(eg)",
"cbc_(eg)",
"cbc-(eg)",
"cbc (jp)",
"cbc.(jp)",
"cbc_(jp)",
"cbc-(jp)",
"cbc gem",
"cbc.gem",
"cbc_gem",
"cbc-gem",
"cbc news network",
"cbc.news.network",
"cbc_news_network",
"cbc-news-network",
"cnn",
"cbs all access",
"cbs.all.access",
"cbs_all_access",
"cbs-all-access",
"caa",
"cbs reality (uk)",
"cbs reality",
"cbsreality",
"cbs.reality.(uk)",
"cbs_reality_(uk)",
"cbs-reality-(uk)",
"cru",
"cbs",
"cbeebies",
"cctv",
"cda",
"cfpl tv",
"cfpl.tv",
"cfpl_tv",
"cfpl-tv",
"cgv",
"chch tv",
"chch.tv",
"chch_tv",
"chch-tv",
"choco tv",
"choco.tv",
"choco_tv",
"choco-tv",
"citv",
"cmt",
"cmtv",
"cn8",
"cnbc tv18",
"cnbc.tv18",
"cnbc_tv18",
"cnbc-tv18",
"cnbc",
"cnni",
"cnews",
"contv",
"cpac",
"crtv",
"cstv",
"cstar",
"ctc (ja)",
"ctc",
"ctc.(ja)",
"ctc_(ja)",
"ctc-(ja)",
"ctc (ru)",
"ctc.(ru)",
"ctc_(ru)",
"ctc-(ru)",
"cts",
"ctv (cn)",
"ctv",
"ctv.(cn)",
"ctv_(cn)",
"ctv-(cn)",
"ctv (jp)",
"ctv.(jp)",
"ctv_(jp)",
"ctv-(jp)",
"ctv (tw)",
"ctv.(tw)",
"ctv_(tw)",
"ctv-(tw)",
"ctv comedy",
"ctv.comedy",
"ctv_comedy",
"ctv-comedy",
"ctv drama",
"ctv.drama",
"ctv_drama",
"ctv-drama",
"ctv sci fi channel",
"ctv.sci.fi.channel",
"ctv_sci_fi_channel",
"ctv-sci-fi-channel",
"csfc",
"ctv sci fi",
"ctv.sci.fi",
"ctv_sci_fi",
"ctv-sci-fi",
"csf",
"cti tv",
"cti.tv",
"cti_tv",
"cti-tv",
"cw seed",
"cw.seed",
"cw_seed",
"cw-seed",
"cable tv",
"cable.tv",
"cable_tv",
"cable-tv",
"canadian learning television",
"canadian.learning.television",
"canadian_learning_television",
"canadian-learning-television",
"clt",
"canal 10 (ar)",
"canal 10",
"canal10",
"canal.10.(ar)",
"canal_10_(ar)",
"canal-10-(ar)",
"c10 a",
"canal 10 saeta",
"canal.10.saeta",
"canal_10_saeta",
"canal-10-saeta",
"c10 s",
"canal 11",
"canal.11",
"canal_11",
"canal-11",
"c11",
"canal 13",
"canal.13",
"canal_13",
"canal-13",
"c13",
"canal 22",
"canal.22",
"canal_22",
"canal-22",
"c22",
"canal 4 montecarlo",
"canal.4.montecarlo",
"canal_4_montecarlo",
"canal-4-montecarlo",
"c4 m",
"canal 5",
"canal.5",
"canal_5",
"canal-5",
"canal 9 (ar)",
"canal 9",
"canal9",
"canal.9.(ar)",
"canal_9_(ar)",
"canal-9-(ar)",
"c9 a",
"canal brasil",
"canal.brasil",
"canal_brasil",
"canal-brasil",
"canal d",
"canal.d",
"canal_d",
"canal-d",
"canal famille",
"canal.famille",
"canal_famille",
"canal-famille",
"canal j",
"canal.j",
"canal_j",
"canal-j",
"canal off",
"canal.off",
"canal_off",
"canal-off",
"canal once",
"canal.once",
"canal_once",
"canal-once",
"canal q",
"canal.q",
"canal_q",
"canal-q",
"canal sur",
"canal.sur",
"canal_sur",
"canal-sur",
"canal vie",
"canal.vie",
"canal_vie",
"canal-vie",
"canal de las estrellas",
"canal.de.las.estrellas",
"canal_de_las_estrellas",
"canal-de-las-estrellas",
"cdle",
"canal+ (es)",
"canal+",
"canal+.(es)",
"canal+_(es)",
"canal+-(es)",
"canal+ cyfrowy",
"canal+.cyfrowy",
"canal+_cyfrowy",
"canal+-cyfrowy",
"canale 5",
"canale.5",
"canale_5",
"canale-5",
"canvas",
"caracol tv",
"caracol.tv",
"caracol_tv",
"caracol-tv",
"carlton central",
"carlton.central",
"carlton_central",
"carlton-central",
"cartoon hangover",
"cartoon.hangover",
"cartoon_hangover",
"cartoon-hangover",
"cartoon network (uk)",
"cartoon network",
"cartoonnetwork",
"cartoon.network.(uk)",
"cartoon_network_(uk)",
"cartoon-network-(uk)",
"cnu",
"cartoon network australia",
"cartoon.network.australia",
"cartoon_network_australia",
"cartoon-network-australia",
"cna",
"cartoon network brasil",
"cartoon.network.brasil",
"cartoon_network_brasil",
"cartoon-network-brasil",
"cnb",
"cartoon.network",
"cartoon_network",
"cartoon-network",
"cartoonito",
"casa",
"caution zero",
"caution.zero",
"caution_zero",
"caution-zero",
"centric",
"challenge",
"channel 101",
"channel.101",
"channel_101",
"channel-101",
"c101",
"channel 2",
"channel.2",
"channel_2",
"channel-2",
"channel 3",
"channel.3",
"channel_3",
"channel-3",
"channel 4",
"channel.4",
"channel_4",
"channel-4",
"channel 5 (sg)",
"channel 5",
"channel5",
"channel.5.(sg)",
"channel_5_(sg)",
"channel-5-(sg)",
"c5 s",
"channel 5 (th)",
"channel.5.(th)",
"channel_5_(th)",
"channel-5-(th)",
"c5 t",
"channel.5",
"channel_5",
"channel-5",
"channel 6",
"channel.6",
"channel_6",
"channel-6",
"channel 7",
"channel.7",
"channel_7",
"channel-7",
"channel 8 (th)",
"channel 8",
"channel8",
"channel.8.(th)",
"channel_8_(th)",
"channel-8-(th)",
"c8 t",
"channel.8",
"channel_8",
"channel-8",
"channel 9",
"channel.9",
"channel_9",
"channel-9",
"channel a",
"channel.a",
"channel_a",
"channel-a",
"channel newsasia",
"channel.newsasia",
"channel_newsasia",
"channel-newsasia",
"channel one",
"channel.one",
"channel_one",
"channel-one",
"channel u",
"channel.u",
"channel_u",
"channel-u",
"channel [v]",
"channel.[v]",
"channel_[v]",
"channel-[v]",
"chart show tv",
"chart.show.tv",
"chart_show_tv",
"chart-show-tv",
"cst",
"chilevisión",
"chiller",
"choice",
"chorus sports",
"chorus.sports",
"chorus_sports",
"chorus-sports",
"christian broadcasting network",
"christian.broadcasting.network",
"christian_broadcasting_network",
"christian-broadcasting-network",
"cbn",
"chubu nippon broadcasting",
"chubu.nippon.broadcasting",
"chubu_nippon_broadcasting",
"chubu-nippon-broadcasting",
"chérie 25",
"chérie.25",
"chérie_25",
"chérie-25",
"c25",
"cielo",
"cine 5",
"cine.5",
"cine_5",
"cine-5",
"cinemax",
"city channel",
"city.channel",
"city_channel",
"city-channel",
"citytv",
"classic arts showcase",
"classic.arts.showcase",
"classic_arts_showcase",
"classic-arts-showcase",
"cas",
"classic fm tv",
"classic.fm.tv",
"classic_fm_tv",
"classic-fm-tv",
"cft",
"cloo (fka sleuth)",
"cloo.(fka.sleuth)",
"cloo_(fka_sleuth)",
"cloo-(fka-sleuth)",
"cfs",
"club illico",
"club.illico",
"club_illico",
"club-illico",
"club rtl",
"club.rtl",
"club_rtl",
"club-rtl",
"colors tv",
"colors.tv",
"colors_tv",
"colors-tv",
"columbia broadcasting system, inc ",
"columbia.broadcasting.system,.inc.",
"columbia_broadcasting_system,_inc_",
"columbia-broadcasting-system,-inc-",
"cbsi",
"comedy central (de)",
"comedy central",
"comedycentral",
"comedy.central.(de)",
"comedy_central_(de)",
"comedy-central-(de)",
"ccd",
"comedy central (es)",
"comedy.central.(es)",
"comedy_central_(es)",
"comedy-central-(es)",
"cce",
"comedy central (fr)",
"comedy.central.(fr)",
"comedy_central_(fr)",
"comedy-central-(fr)",
"ccf",
"comedy central (latin america)",
"comedy.central.(latin.america)",
"comedy_central_(latin_america)",
"comedy-central-(latin-america)",
"ccla",
"comedy central (uk)",
"comedy.central.(uk)",
"comedy_central_(uk)",
"comedy-central-(uk)",
"ccu",
"comedy.central",
"comedy_central",
"comedy-central",
"comic con hq",
"comic.con.hq",
"comic_con_hq",
"comic-con-hq",
"cch",
"community channel",
"community.channel",
"community_channel",
"community-channel",
"comédie !",
"comédie.!",
"comédie_!",
"comédie-!",
"comédie+",
"conmebol tv",
"conmebol.tv",
"conmebol_tv",
"conmebol-tv",
"contar",
"cooking channel",
"cooking.channel",
"cooking_channel",
"cooking-channel",
"cosmopolitan tv",
"cosmopolitan.tv",
"cosmopolitan_tv",
"cosmopolitan-tv",
"cottage life",
"cottage.life",
"cottage_life",
"cottage-life",
"coture",
"couleur 3",
"couleur.3",
"couleur_3",
"couleur-3",
"court tv",
"court.tv",
"court_tv",
"court-tv",
"crackle",
"crave",
"crime & investigation network (au)",
"crime & investigation network",
"crime&investigationnetwork",
"crime.&.investigation.network.(au)",
"crime_&_investigation_network_(au)",
"crime-&-investigation-network-(au)",
"c&ina",
"crime & investigation network (europe)",
"crime.&.investigation.network.(europe)",
"crime_&_investigation_network_(europe)",
"crime-&-investigation-network-(europe)",
"c&ine",
"crime & investigation network (uk)",
"crime.&.investigation.network.(uk)",
"crime_&_investigation_network_(uk)",
"crime-&-investigation-network-(uk)",
"c&inu",
"crime & investigation network (us)",
"crime.&.investigation.network.(us)",
"crime_&_investigation_network_(us)",
"crime-&-investigation-network-(us)",
"cuatro",
"curiositystream",
"current tv",
"current.tv",
"current_tv",
"current-tv",
"cw",
"dc universe",
"dc.universe",
"dc_universe",
"dc-universe",
"dd gujarati",
"dd.gujarati",
"dd_gujarati",
"dd-gujarati",
"ddr1",
"diy network canada",
"diy.network.canada",
"diy_network_canada",
"diy-network-canada",
"dnc",
"diy network",
"diy.network",
"diy_network",
"diy-network",
"dmax (de)",
"dmax",
"dmax.(de)",
"dmax_(de)",
"dmax-(de)",
"dmax (it)",
"dmax.(it)",
"dmax_(it)",
"dmax-(it)",
"dmc",
"dr k",
"dr.k",
"dr_k",
"dr-k",
"dr ramasjang",
"dr.ramasjang",
"dr_ramasjang",
"dr-ramasjang",
"dr ultra",
"dr.ultra",
"dr_ultra",
"dr-ultra",
"dr1",
"dr2",
"dr3",
"dramacube",
"dropout",
"dw (arabia)",
"dw.(arabia)",
"dw_(arabia)",
"dw-(arabia)",
"daai tv",
"daai.tv",
"daai_tv",
"daai-tv",
"dailymotion",
"dark",
"das erste",
"das.erste",
"das_erste",
"das-erste",
"daum tvpot",
"daum.tvpot",
"daum_tvpot",
"daum-tvpot",
"dave",
"dawn news",
"dawn.news",
"dawn_news",
"dawn-news",
"deportv",
"destination america",
"destination.america",
"destination_america",
"destination-america",
"deutsche welle tv",
"deutsche.welle.tv",
"deutsche_welle_tv",
"deutsche-welle-tv",
"dwt",
"direct to video",
"direct.to.video",
"direct_to_video",
"direct-to-video",
"dtv",
"discovery (nl)",
"discovery",
"discovery.(nl)",
"discovery_(nl)",
"discovery-(nl)",
"discovery channel (au)",
"discovery channel",
"discoverychannel",
"discovery.channel.(au)",
"discovery_channel_(au)",
"discovery-channel-(au)",
"dca",
"discovery channel (asia)",
"discovery.channel.(asia)",
"discovery_channel_(asia)",
"discovery-channel-(asia)",
"discovery channel (ca)",
"discovery.channel.(ca)",
"discovery_channel_(ca)",
"discovery-channel-(ca)",
"dcc",
"discovery channel (pl)",
"discovery.channel.(pl)",
"discovery_channel_(pl)",
"discovery-channel-(pl)",
"dcp",
"discovery channel (se)",
"discovery.channel.(se)",
"discovery_channel_(se)",
"discovery-channel-(se)",
"dcs",
"discovery channel (uk)",
"discovery.channel.(uk)",
"discovery_channel_(uk)",
"discovery-channel-(uk)",
"dcu",
"discovery family",
"discovery.family",
"discovery_family",
"discovery-family",
"discovery go",
"discovery.go",
"discovery_go",
"discovery-go",
"discovery hd world",
"discovery.hd.world",
"discovery_hd_world",
"discovery-hd-world",
"dhw",
"discovery history",
"discovery.history",
"discovery_history",
"discovery-history",
"discovery kids",
"discovery.kids",
"discovery_kids",
"discovery-kids",
"discovery life",
"discovery.life",
"discovery_life",
"discovery-life",
"discovery max",
"discovery.max",
"discovery_max",
"discovery-max",
"discovery science",
"discovery.science",
"discovery_science",
"discovery-science",
"discovery shed",
"discovery.shed",
"discovery_shed",
"discovery-shed",
"discovery turbo uk",
"discovery.turbo.uk",
"discovery_turbo_uk",
"discovery-turbo-uk",
"dtu",
"discovery turbo",
"discovery.turbo",
"discovery_turbo",
"discovery-turbo",
"discovery+ (se)",
"discovery+",
"discovery+.(se)",
"discovery+_(se)",
"discovery+-(se)",
"dish tv",
"dish.tv",
"dish_tv",
"dish-tv",
"disney channel (br)",
"disney channel",
"disneychannel",
"disney.channel.(br)",
"disney_channel_(br)",
"disney-channel-(br)",
"dcb",
"disney channel (de)",
"disney.channel.(de)",
"disney_channel_(de)",
"disney-channel-(de)",
"dcd",
"disney channel (fr)",
"disney.channel.(fr)",
"disney_channel_(fr)",
"disney-channel-(fr)",
"dcf",
"disney channel (it)",
"disney.channel.(it)",
"disney_channel_(it)",
"disney-channel-(it)",
"dci",
"disney channel (latin america)",
"disney.channel.(latin.america)",
"disney_channel_(latin_america)",
"disney-channel-(latin-america)",
"dcla",
"disney channel (nl)",
"disney.channel.(nl)",
"disney_channel_(nl)",
"disney-channel-(nl)",
"dcn",
"disney channel (uk)",
"disney.channel.(uk)",
"disney_channel_(uk)",
"disney-channel-(uk)",
"disney.channel",
"disney_channel",
"disney-channel",
"disney cinemagic",
"disney.cinemagic",
"disney_cinemagic",
"disney-cinemagic",
"disney junior (uk)",
"disney junior",
"disneyjunior",
"disney.junior.(uk)",
"disney_junior_(uk)",
"disney-junior-(uk)",
"dju",
"disney.junior",
"disney_junior",
"disney-junior",
"disney xd (latin america)",
"disney.xd.(latin.america)",
"disney_xd_(latin_america)",
"disney-xd-(latin-america)",
"dxla",
"disney xd",
"disney.xd",
"disney_xd",
"disney-xd",
"disney+ hotstar",
"disney+.hotstar",
"disney+_hotstar",
"disney+-hotstar",
"disney+",
"disneylife",
"dlife",
"doordarshan national",
"doordarshan.national",
"doordarshan_national",
"doordarshan-national",
"doordarshan news",
"doordarshan.news",
"doordarshan_news",
"doordarshan-news",
"doordarshan sports",
"doordarshan.sports",
"doordarshan_sports",
"doordarshan-sports",
"dost tv",
"dost.tv",
"dost_tv",
"dost-tv",
"draemong",
"dragon tv",
"dragon.tv",
"dragon_tv",
"dragon-tv",
"dramah",
"dramax",
"dreamworks channel",
"dreamworks.channel",
"dreamworks_channel",
"dreamworks-channel",
"drinktv",
"dumont television network",
"dumont.television.network",
"dumont_television_network",
"dumont-television-network",
"dtn",
"duck tv",
"duck.tv",
"duck_tv",
"duck-tv",
"duna tv",
"duna.tv",
"duna_tv",
"duna-tv",
"e! (ca)",
"e!.(ca)",
"e!_(ca)",
"e!-(ca)",
"e channel",
"e.channel",
"e_channel",
"e-channel",
"ebs",
"entv",
"epic tv",
"epic.tv",
"epic_tv",
"epic-tv",
"epix",
"ert",
"espn asia",
"espn.asia",
"espn_asia",
"espn-asia",
"espn hong kong",
"espn.hong.kong",
"espn_hong_kong",
"espn-hong-kong",
"ehk",
"espn india",
"espn.india",
"espn_india",
"espn-india",
"espn philippines",
"espn.philippines",
"espn_philippines",
"espn-philippines",
"espn taiwan",
"espn.taiwan",
"espn_taiwan",
"espn-taiwan",
"espn+",
"espn2",
"espn",
"etb1",
"etb2",
"ettv yoyo",
"ettv.yoyo",
"ettv_yoyo",
"ettv-yoyo",
"ettv",
"etv gujarati",
"etv.gujarati",
"etv_gujarati",
"etv-gujarati",
"etv",
"earwolf podcast network",
"earwolf.podcast.network",
"earwolf_podcast_network",
"earwolf-podcast-network",
"epn",
"ebonylife tv",
"ebonylife.tv",
"ebonylife_tv",
"ebonylife-tv",
"echorouk tv",
"echorouk.tv",
"echorouk_tv",
"echorouk-tv",
"eden",
"einsplus",
"einsfestival",
"el djazairia one",
"el.djazairia.one",
"el_djazairia_one",
"el-djazairia-one",
"edo",
"el garage tv",
"el.garage.tv",
"el_garage_tv",
"el-garage-tv",
"egt",
"el khabar broadcasting company (kbc)",
"el khabar broadcasting company",
"elkhabarbroadcastingcompany",
"el.khabar.broadcasting.company.(kbc)",
"el_khabar_broadcasting_company_(kbc)",
"el-khabar-broadcasting-company-(kbc)",
"ekbck",
"el rey network",
"el.rey.network",
"el_rey_network",
"el-rey-network",
"ern",
"el trece",
"el.trece",
"el_trece",
"el-trece",
"eleven",
"elisa viihde viaplay",
"elisa.viihde.viaplay",
"elisa_viihde_viaplay",
"elisa-viihde-viaplay",
"evv",
"elisa viihde",
"elisa.viihde",
"elisa_viihde",
"elisa-viihde",
"elle girl",
"elle.girl",
"elle_girl",
"elle-girl",
"encore",
"encuentro",
"epsilon tv",
"epsilon.tv",
"epsilon_tv",
"epsilon-tv",
"eros now",
"eros.now",
"eros_now",
"eros-now",
"esquire network",
"esquire.network",
"esquire_network",
"esquire-network",
"estação cultura da tve",
"estação.cultura.da.tve",
"estação_cultura_da_tve",
"estação-cultura-da-tve",
"ecdt",
"european broadcasting union (ebu)",
"european broadcasting union",
"europeanbroadcastingunion",
"european.broadcasting.union.(ebu)",
"european_broadcasting_union_(ebu)",
"european-broadcasting-union-(ebu)",
"ebue",
"eurosport",
"explora",
"express entertainment",
"express.entertainment",
"express_entertainment",
"express-entertainment",
"expresso",
"exxen",
"f1tv",
"fearnet",
"fem",
"fod",
"fox reality",
"fox.reality",
"fox_reality",
"fox-reality",
"fox sports 1",
"fox.sports.1",
"fox_sports_1",
"fox-sports-1",
"fs1",
"fox traveller",
"fox.traveller",
"fox_traveller",
"fox-traveller",
"fox türkiye",
"fox.türkiye",
"fox_türkiye",
"fox-türkiye",
"fox+",
"fox",
"ftv",
"funimation channel",
"funimation.channel",
"funimation_channel",
"funimation-channel",
"fx (br)",
"fx.(br)",
"fx_(br)",
"fx-(br)",
"fx (latin america)",
"fx.(latin.america)",
"fx_(latin_america)",
"fx-(latin-america)",
"fla",
"fxx",
"fyi",
"facebook watch",
"facebook.watch",
"facebook_watch",
"facebook-watch",
"family (ca)",
"family",
"family.(ca)",
"family_(ca)",
"family-(ca)",
"family chrgd",
"family.chrgd",
"family_chrgd",
"family-chrgd",
"family gekijo",
"family.gekijo",
"family_gekijo",
"family-gekijo",
"fantastic tv",
"fantastic.tv",
"fantastic_tv",
"fantastic-tv",
"fashion tv",
"fashion.tv",
"fashion_tv",
"fashion-tv",
"feeln",
"filles tv",
"filles.tv",
"filles_tv",
"filles-tv",
"filmon tv",
"filmon.tv",
"filmon_tv",
"filmon-tv",
"five life",
"five.life",
"five_life",
"five-life",
"five us",
"five.us",
"five_us",
"five-us",
"fix & foxi",
"fix.&.foxi",
"fix_&_foxi",
"fix-&-foxi",
"f&f",
"flooxer",
"floptv",
"food network canada",
"food.network.canada",
"food_network_canada",
"food-network-canada",
"fnc",
"food network kitchen",
"food.network.kitchen",
"food_network_kitchen",
"food-network-kitchen",
"fnk",
"food network",
"food.network",
"food_network",
"food-network",
"forever dog",
"forever.dog",
"forever_dog",
"forever-dog",
"formula 1 tv",
"formula.1.tv",
"formula_1_tv",
"formula-1-tv",
"f1 t",
"fox 1 (latin america)",
"fox.1.(latin.america)",
"fox_1_(latin_america)",
"fox-1-(latin-america)",
"f1 la",
"fox action (latin america)",
"fox.action.(latin.america)",
"fox_action_(latin_america)",
"fox-action-(latin-america)",
"fala",
"fox action movies",
"fox.action.movies",
"fox_action_movies",
"fox-action-movies",
"fam",
"fox business",
"fox.business",
"fox_business",
"fox-business",
"fox channel (de)",
"fox channel",
"foxchannel",
"fox.channel.(de)",
"fox_channel_(de)",
"fox-channel-(de)",
"fcd",
"fox channel (fi)",
"fox.channel.(fi)",
"fox_channel_(fi)",
"fox-channel-(fi)",
"fcf",
"fox channel (it)",
"fox.channel.(it)",
"fox_channel_(it)",
"fox-channel-(it)",
"fci",
"fox channel (uk)",
"fox.channel.(uk)",
"fox_channel_(uk)",
"fox-channel-(uk)",
"fcu",
"fox cinéma",
"fox.cinéma",
"fox_cinéma",
"fox-cinéma",
"fox classics",
"fox.classics",
"fox_classics",
"fox-classics",
"fox crime",
"fox.crime",
"fox_crime",
"fox-crime",
"fox españa",
"fox.españa",
"fox_españa",
"fox-españa",
"fox family (latin america)",
"fox.family.(latin.america)",
"fox_family_(latin_america)",
"fox-family-(latin-america)",
"ffla",
"fox family",
"fox.family",
"fox_family",
"fox-family",
"fox kids",
"fox.kids",
"fox_kids",
"fox-kids",
"fox life (it)",
"fox life",
"foxlife",
"fox.life.(it)",
"fox_life_(it)",
"fox-life-(it)",
"fli",
"fox movies",
"fox.movies",
"fox_movies",
"fox-movies",
"fox nation",
"fox.nation",
"fox_nation",
"fox-nation",
"fox news",
"fox.news",
"fox_news",
"fox-news",
"fox showcase",
"fox.showcase",
"fox_showcase",
"fox-showcase",
"fox sports (au)",
"fox sports",
"foxsports",
"fox.sports.(au)",
"fox_sports_(au)",
"fox-sports-(au)",
"fsa",
"fox sports 2",
"fox.sports.2",
"fox_sports_2",
"fox-sports-2",
"fs2",
"fox sports net",
"fox.sports.net",
"fox_sports_net",
"fox-sports-net",
"fsn",
"fox telecolombia",
"fox.telecolombia",
"fox_telecolombia",
"fox-telecolombia",
"fox8",
"foxtel arts",
"foxtel.arts",
"foxtel_arts",
"foxtel-arts",
"france 2",
"france.2",
"france_2",
"france-2",
"france 3",
"france.3",
"france_3",
"france-3",
"france 4",
"france.4",
"france_4",
"france-4",
"france 5",
"france.5",
"france_5",
"france-5",
"france inter",
"france.inter",
"france_inter",
"france-inter",
"france Ô",
"france.Ô",
"france_Ô",
"france-Ô",
"fred tv",
"fred.tv",
"fred_tv",
"fred-tv",
"freeform",
"frissons tv",
"frissons.tv",
"frissons_tv",
"frissons-tv",
"fuel tv",
"fuel.tv",
"fuel_tv",
"fuel-tv",
"fuji tv",
"fuji.tv",
"fuji_tv",
"fuji-tv",
"fullscreen",
"fuse",
"fusion",
"futura",
"g4 canada",
"g4.canada",
"g4_canada",
"g4-canada",
"g4c",
"gain",
"geo super",
"geo.super",
"geo_super",
"geo-super",
"gma",
"gmc tv",
"gmc.tv",
"gmc_tv",
"gmc-tv",
"gmm one",
"gmm.one",
"gmm_one",
"gmm-one",
"gmm25",
"gnt",
"gtv",
"gyao!",
"gagaoolala",
"gaia",
"game one",
"game.one",
"game_one",
"game-one",
"game show network",
"game.show.network",
"game_show_network",
"game-show-network",
"gsn",
"gametv canada",
"gametv.canada",
"gametv_canada",
"gametv-canada",
"gazeta",
"geo tv",
"geo.tv",
"geo_tv",
"geo-tv",
"global",
"globonews",
"globoplay",
"gloob",
"go90",
"goplay",
"golf channel",
"golf.channel",
"golf_channel",
"golf-channel",
"great american country",
"great.american.country",
"great_american_country",
"great-american-country",
"gac",
"guardian television network",
"guardian.television.network",
"guardian_television_network",
"guardian-television-network",
"gtn",
"gulli",
"hbo asia",
"hbo.asia",
"hbo_asia",
"hbo-asia",
"hbo canada",
"hbo.canada",
"hbo_canada",
"hbo-canada",
"hbo españa",
"hbo.españa",
"hbo_españa",
"hbo-españa",
"hbo europe",
"hbo.europe",
"hbo_europe",
"hbo-europe",
"hbo latin america",
"hbo.latin.america",
"hbo_latin_america",
"hbo-latin-america",
"hla",
"hbo magyarország",
"hbo.magyarország",
"hbo_magyarország",
"hbo-magyarország",
"hbo max",
"hbo.max",
"hbo_max",
"hbo-max",
"hbo nordic",
"hbo.nordic",
"hbo_nordic",
"hbo-nordic",
"hbo",
"hdnet",
"hgtv canada",
"hgtv.canada",
"hgtv_canada",
"hgtv-canada",
"hgtv",
"hifi",
"hktv",
"hln",
"hot",
"human",
"hakka tv",
"hakka.tv",
"hakka_tv",
"hakka-tv",
"hallmark channel",
"hallmark.channel",
"hallmark_channel",
"hallmark-channel",
"hallmark movies & mysteries",
"hallmark.movies.&.mysteries",
"hallmark_movies_&_mysteries",
"hallmark-movies-&-mysteries",
"hm&m",
"hallmark movies now",
"hallmark.movies.now",
"hallmark_movies_now",
"hallmark-movies-now",
"hmn",
"heartland",
"hikari tv",
"hikari.tv",
"hikari_tv",
"hikari-tv",
"histoire",
"historia (ca)",
"historia",
"historia.(ca)",
"historia_(ca)",
"historia-(ca)",
"historia (es)",
"historia.(es)",
"historia_(es)",
"historia-(es)",
"history (uk)",
"history",
"history.(uk)",
"history_(uk)",
"history-(uk)",
"history canada",
"history.canada",
"history_canada",
"history-canada",
"hoichoi",
"hokkaido television broadcasting",
"hokkaido.television.broadcasting",
"hokkaido_television_broadcasting",
"hokkaido-television-broadcasting",
"htb",
"hrvatska radiotelevizija",
"hrvatska.radiotelevizija",
"hrvatska_radiotelevizija",
"hrvatska-radiotelevizija",
"hulu",
"hum tv",
"hum.tv",
"hum_tv",
"hum-tv",
"hunan tv",
"hunan.tv",
"hunan_tv",
"hunan-tv",
"hungama",
"hír tv",
"hír.tv",
"hír_tv",
"hír-tv",
"ib3",
"ice tv",
"ice.tv",
"ice_tv",
"ice-tv",
"ici tou tv",
"ici.tou.tv",
"ici_tou_tv",
"ici-tou-tv",
"itt",
"ici télé",
"ici.télé",
"ici_télé",
"ici-télé",
"ictv",
"ifc",
"ikon",
"imdb tv",
"imdb.tv",
"imdb_tv",
"imdb-tv",
"insp",
"irib tv1",
"irib.tv1",
"irib_tv1",
"irib-tv1",
"itv central",
"itv.central",
"itv_central",
"itv-central",
"itv cymru wales",
"itv.cymru.wales",
"itv_cymru_wales",
"itv-cymru-wales",
"icw",
"itv encore",
"itv.encore",
"itv_encore",
"itv-encore",
"itv granada",
"itv.granada",
"itv_granada",
"itv-granada",
"itv hub",
"itv.hub",
"itv_hub",
"itv-hub",
"itv1",
"itv2",
"itv3",
"itv4",
"itv",
"itvbe",
"itvx",
"imagen televisión",
"imagen.televisión",
"imagen_televisión",
"imagen-televisión",
"imago tv",
"imago.tv",
"imago_tv",
"imago-tv",
"independent television network",
"independent.television.network",
"independent_television_network",
"independent-television-network",
"itn",
"indus music",
"indus.music",
"indus_music",
"indus-music",
"indus news",
"indus.news",
"indus_news",
"indus-news",
"indus vision",
"indus.vision",
"indus_vision",
"indus-vision",
"indycarlive",
"infinity",
"insight tv",
"insight.tv",
"insight_tv",
"insight-tv",
"instagram / igtv",
"instagram./.igtv",
"instagram_/_igtv",
"instagram-/-igtv",
"i/i",
"investigation discovery",
"investigation.discovery",
"investigation_discovery",
"investigation-discovery",
"investigation",
"ion television",
"ion.television",
"ion_television",
"ion-television",
"italia 1",
"italia.1",
"italia_1",
"italia-1",
"jim",
"jtbc2",
"jw org",
"jw.org",
"jw_org",
"jw-org",
"jeuxvideo com",
"jeuxvideo.com",
"jeuxvideo_com",
"jeuxvideo-com",
"jiangsu tv",
"jiangsu.tv",
"jiangsu_tv",
"jiangsu-tv",
"joi",
"joiz (ch)",
"joiz",
"joiz.(ch)",
"joiz_(ch)",
"joiz-(ch)",
"joiz (de)",
"joiz.(de)",
"joiz_(de)",
"joiz-(de)",
"joyn",
"june",
"jupiter broadcasting",
"jupiter.broadcasting",
"jupiter_broadcasting",
"jupiter-broadcasting",
"kbs 1",
"kbs.1",
"kbs_1",
"kbs-1",
"kbs 2",
"kbs.2",
"kbs_2",
"kbs-2",
"kbs joy",
"kbs.joy",
"kbs_joy",
"kbs-joy",
"kbs world",
"kbs.world",
"kbs_world",
"kbs-world",
"kbs",
"kcet",
"kika",
"kktv",
"kpn presenteert",
"kpn.presenteert",
"kpn_presenteert",
"kpn-presenteert",
"kro ncrv",
"kro.ncrv",
"kro_ncrv",
"kro-ncrv",
"kro",
"ktn",
"kvos",
"kabel eins",
"kabel.eins",
"kabel_eins",
"kabel-eins",
"kakao tv",
"kakao.tv",
"kakao_tv",
"kakao-tv",
"kampüs tv",
"kampüs.tv",
"kampüs_tv",
"kampüs-tv",
"kan",
"kanaaltwee",
"kanal 4 (dk)",
"kanal 4",
"kanal4",
"kanal.4.(dk)",
"kanal_4_(dk)",
"kanal-4-(dk)",
"k4 d",
"kanal 5 (dk)",
"kanal 5",
"kanal5",
"kanal.5.(dk)",
"kanal_5_(dk)",
"kanal-5-(dk)",
"k5 d",
"kanal 5 (se)",
"kanal.5.(se)",
"kanal_5_(se)",
"kanal-5-(se)",
"k5 s",
"kanal 7",
"kanal.7",
"kanal_7",
"kanal-7",
"kanal a (tr)",
"kanal a",
"kanala",
"kanal.a.(tr)",
"kanal_a_(tr)",
"kanal-a-(tr)",
"kat",
"kanal d romania",
"kanal.d.romania",
"kanal_d_romania",
"kanal-d-romania",
"kdr",
"kanal d",
"kanal.d",
"kanal_d",
"kanal-d",
"kansai tv",
"kansai.tv",
"kansai_tv",
"kansai-tv",
"kashish tv",
"kashish.tv",
"kashish_tv",
"kashish-tv",
"kerrang! tv",
"kerrang!.tv",
"kerrang!_tv",
"kerrang!-tv",
"keshet 12",
"keshet.12",
"keshet_12",
"keshet-12",
"k12",
"keshet",
"ketnet",
"kids station",
"kids.station",
"kids_station",
"kids-station",
"kids and teens tv",
"kids.and.teens.tv",
"kids_and_teens_tv",
"kids-and-teens-tv",
"katt",
"kinopoisk",
"kiss",
"knowledge network",
"knowledge.network",
"knowledge_network",
"knowledge-network",
"korean central television",
"korean.central.television",
"korean_central_television",
"korean-central-television",
"kct",
"kunskapskanalen",
"kyoto broadcasting system",
"kyoto.broadcasting.system",
"kyoto_broadcasting_system",
"kyoto-broadcasting-system",
"kyushu asahi broadcasting (kbc)",
"kyushu asahi broadcasting",
"kyushuasahibroadcasting",
"kyushu.asahi.broadcasting.(kbc)",
"kyushu_asahi_broadcasting_(kbc)",
"kyushu-asahi-broadcasting-(kbc)",
"kabk",
"kyushu.asahi.broadcasting",
"kyushu_asahi_broadcasting",
"kyushu-asahi-broadcasting",
"kab",
"l'Équipe 21",
"l'Équipe.21",
"l'Équipe_21",
"l'Équipe-21",
"l21",
"lci",
"line tv (th)",
"line tv",
"linetv",
"line.tv.(th)",
"line_tv_(th)",
"line-tv-(th)",
"ltt",
"lmn",
"lnk tv",
"lnk.tv",
"lnk_tv",
"lnk-tv",
"logo",
"la 2 (tve2)",
"la.2.(tve2)",
"la_2_(tve2)",
"la-2-(tve2)",
"l2 t",
"la cinq",
"la.cinq",
"la_cinq",
"la-cinq",
"la deux",
"la.deux",
"la_deux",
"la-deux",
"la red",
"la.red",
"la_red",
"la-red",
"la siete",
"la.siete",
"la_siete",
"la-siete",
"la trois",
"la.trois",
"la_trois",
"la-trois",
"la une",
"la.une",
"la_une",
"la-une",
"la uno (tve1)",
"la.uno.(tve1)",
"la_uno_(tve1)",
"la-uno-(tve1)",
"lut",
"la5",
"la7",
"lasexta",
"lebanese broadcasting corporation international",
"lebanese.broadcasting.corporation.international",
"lebanese_broadcasting_corporation_international",
"lebanese-broadcasting-corporation-international",
"lbci",
"lewspears (australia)",
"lewspears",
"lewspears.(australia)",
"lewspears_(australia)",
"lewspears-(australia)",
"liberty channel",
"liberty.channel",
"liberty_channel",
"liberty-channel",
"liberty tv",
"liberty.tv",
"liberty_tv",
"liberty-tv",
"libya al ahrar tv",
"libya.al.ahrar.tv",
"libya_al_ahrar_tv",
"libya-al-ahrar-tv",
"laat",
"libya al riadhiya",
"libya.al.riadhiya",
"libya_al_riadhiya",
"libya-al-riadhiya",
"lar",
"libya alhurra tv",
"libya.alhurra.tv",
"libya_alhurra_tv",
"libya-alhurra-tv",
"lat",
"libya awalan tv",
"libya.awalan.tv",
"libya_awalan_tv",
"libya-awalan-tv",
"life ok",
"life.ok",
"life_ok",
"life-ok",
"lifestyle food",
"lifestyle.food",
"lifestyle_food",
"lifestyle-food",
"lifestyle home",
"lifestyle.home",
"lifestyle_home",
"lifestyle-home",
"lifestyle",
"lifetime (uk)",
"lifetime",
"lifetime.(uk)",
"lifetime_(uk)",
"lifetime-(uk)",
"lifetime korea",
"lifetime.korea",
"lifetime_korea",
"lifetime-korea",
"line.tv",
"line_tv",
"line-tv",
"live well network",
"live.well.network",
"live_well_network",
"live-well-network",
"lwn",
"living",
"london live",
"london.live",
"london_live",
"london-live",
"longhorn network",
"longhorn.network",
"longhorn_network",
"longhorn-network",
"lâlegül tv",
"lâlegül.tv",
"lâlegül_tv",
"lâlegül-tv",
"m net",
"m.net",
"m_net",
"m-net",
"matv",
"max",
"mbc 1",
"mbc.1",
"mbc_1",
"mbc-1",
"mbc 4 (uae)",
"mbc 4",
"mbc4",
"mbc.4.(uae)",
"mbc_4_(uae)",
"mbc-4-(uae)",
"m4 u",
"mbc drama (uae)",
"mbc drama",
"mbcdrama",
"mbc.drama.(uae)",
"mbc_drama_(uae)",
"mbc-drama-(uae)",
"mdu",
"mbc.drama",
"mbc_drama",
"mbc-drama",
"mbc every1",
"mbc.every1",
"mbc_every1",
"mbc-every1",
"mbc masr",
"mbc.masr",
"mbc_masr",
"mbc-masr",
"mbc plus media",
"mbc.plus.media",
"mbc_plus_media",
"mbc-plus-media",
"mpm",
"mbc queen",
"mbc.queen",
"mbc_queen",
"mbc-queen",
"mbc",
"mbn",
"mbs",
"mce tv (ma chaîne Étudiante)",
"mce.tv.(ma.chaîne.Étudiante)",
"mce_tv_(ma_chaîne_Étudiante)",
"mce-tv-(ma-chaîne-Étudiante)",
"mtmc�",
"mcm",
"mcot",
"mdr",
"mega",
"mlb network",
"mlb.network",
"mlb_network",
"mlb-network",
"mnn",
"msnbc",
"mtv (au/nz)",
"mtv",
"mtv.(au/nz)",
"mtv_(au/nz)",
"mtv-(au/nz)",
"mtv (ca)",
"mtv.(ca)",
"mtv_(ca)",
"mtv-(ca)",
"mtv (fr)",
"mtv.(fr)",
"mtv_(fr)",
"mtv-(fr)",
"mtv (lebanon)",
"mtv.(lebanon)",
"mtv_(lebanon)",
"mtv-(lebanon)",
"mtv (pl)",
"mtv.(pl)",
"mtv_(pl)",
"mtv-(pl)",
"mtv (uk)",
"mtv.(uk)",
"mtv_(uk)",
"mtv-(uk)",
"mtv base",
"mtv.base",
"mtv_base",
"mtv-base",
"mtv brazil",
"mtv.brazil",
"mtv_brazil",
"mtv-brazil",
"mtv dance",
"mtv.dance",
"mtv_dance",
"mtv-dance",
"mtv españa",
"mtv.españa",
"mtv_españa",
"mtv-españa",
"mtv hits",
"mtv.hits",
"mtv_hits",
"mtv-hits",
"mtv india",
"mtv.india",
"mtv_india",
"mtv-india",
"mtv italia",
"mtv.italia",
"mtv_italia",
"mtv-italia",
"mtv latin america",
"mtv.latin.america",
"mtv_latin_america",
"mtv-latin-america",
"mla",
"mtv live",
"mtv.live",
"mtv_live",
"mtv-live",
"mtv mandarin",
"mtv.mandarin",
"mtv_mandarin",
"mtv-mandarin",
"mtv2",
"mtv3",
"mutv",
"magentatv",
"magic",
"magnolia network",
"magnolia.network",
"magnolia_network",
"magnolia-network",
"magyar televízió",
"magyar.televízió",
"magyar_televízió",
"magyar-televízió",
"mais na tela",
"mais.na.tela",
"mais_na_tela",
"mais-na-tela",
"mnt",
"mango tv",
"mango.tv",
"mango_tv",
"mango-tv",
"masterclass",
"mavtv",
"maxdome",
"mevue (usa)",
"mevue",
"mevue.(usa)",
"mevue_(usa)",
"mevue-(usa)",
"mediaset",
"mega channel",
"mega.channel",
"mega_channel",
"mega-channel",
"military channel",
"military.channel",
"military_channel",
"military-channel",
"mnet",
"moi & cie",
"moi.&.cie",
"moi_&_cie",
"moi-&-cie",
"m&c",
"mondo tv",
"mondo.tv",
"mondo_tv",
"mondo-tv",
"moontv",
"more4",
"motortrend",
"movistar+",
"much tv",
"much.tv",
"much_tv",
"much-tv",
"much",
"muchmusic",
"multishow",
"musiqueplus",
"mynetworktv",
"mytf1",
"mya",
"māori television",
"māori.television",
"māori_television",
"māori-television",
"naver tvcast",
"naver.tvcast",
"naver_tvcast",
"naver-tvcast",
"nba tv",
"nba.tv",
"nba_tv",
"nba-tv",
"nbc sports network",
"nbc.sports.network",
"nbc_sports_network",
"nbc-sports-network",
"nsn",
"nbc",
"ncrv",
"ndr",
"ndtv 24x7",
"ndtv.24x7",
"ndtv_24x7",
"ndtv-24x7",
"n24x",
"ndtv good times",
"ndtv.good.times",
"ndtv_good_times",
"ndtv-good-times",
"ngt",
"ndtv india",
"ndtv.india",
"ndtv_india",
"ndtv-india",
"neco",
"net 5",
"net.5",
"net_5",
"net-5",
"net tv",
"net.tv",
"net_tv",
"net-tv",
"net ",
"net.",
"net_",
"net-",
"nfl network",
"nfl.network",
"nfl_network",
"nfl-network",
"nhk bs1",
"nhk.bs1",
"nhk_bs1",
"nhk-bs1",
"nhk educational tv",
"nhk.educational.tv",
"nhk_educational_tv",
"nhk-educational-tv",
"net",
"nhk",
"nhl network",
"nhl.network",
"nhl_network",
"nhl-network",
"nhnz",
"nos",
"nove",
"npo 1",
"npo.1",
"npo_1",
"npo-1",
"nrj 12",
"nrj.12",
"nrj_12",
"nrj-12",
"n12",
"nrk super",
"nrk.super",
"nrk_super",
"nrk-super",
"nrk1",
"nrk2",
"nrk3",
"nt1",
"nta",
"ntr",
"ntv (tw)",
"ntv",
"ntv.(tw)",
"ntv_(tw)",
"ntv-(tw)",
"ntv7",
"nagoya broadcasting network",
"nagoya.broadcasting.network",
"nagoya_broadcasting_network",
"nagoya-broadcasting-network",
"nbn",
"namava",
"nat geo kids (br)",
"nat geo kids",
"natgeokids",
"nat.geo.kids.(br)",
"nat_geo_kids_(br)",
"nat-geo-kids-(br)",
"ngkb",
"national geographic (au/nz)",
"national geographic",
"nationalgeographic",
"national.geographic.(au/nz)",
"national_geographic_(au/nz)",
"national-geographic-(au/nz)",
"nga",
"national geographic (bg)",
"national.geographic.(bg)",
"national_geographic_(bg)",
"national-geographic-(bg)",
"ngb",
"national geographic (fi)",
"national.geographic.(fi)",
"national_geographic_(fi)",
"national-geographic-(fi)",
"ngf",
"national geographic (uk)",
"national.geographic.(uk)",
"national_geographic_(uk)",
"national-geographic-(uk)",
"ngu",
"national geographic channel",
"national.geographic.channel",
"national_geographic_channel",
"national-geographic-channel",
"ngc",
"national geographic wild",
"national.geographic.wild",
"national_geographic_wild",
"national-geographic-wild",
"ngw",
"national.geographic",
"national_geographic",
"national-geographic",
"national media authority",
"national.media.authority",
"national_media_authority",
"national-media-authority",
"nma",
"nebula",
"nederlandse publieke omroep 3",
"nederlandse.publieke.omroep.3",
"nederlandse_publieke_omroep_3",
"nederlandse-publieke-omroep-3",
"npo3",
"nelonen",
"neox",
"netflix",
"network ten",
"network.ten",
"network_ten",
"network-ten",
"new tang dynasty tv",
"new.tang.dynasty.tv",
"new_tang_dynasty_tv",
"new-tang-dynasty-tv",
"ntdt",
"news one",
"news.one",
"news_one",
"news-one",
"nick app",
"nick.app",
"nick_app",
"nick-app",
"nick gas",
"nick.gas",
"nick_gas",
"nick-gas",
"nick jr ",
"nick.jr.",
"nick_jr_",
"nick-jr-",
"nick at nite",
"nick.at.nite",
"nick_at_nite",
"nick-at-nite",
"nan",
"nicktoons",
"nickelodeon (latin america)",
"nickelodeon.(latin.america)",
"nickelodeon_(latin_america)",
"nickelodeon-(latin-america)",
"nla",
"nickelodeon",
"niconico",
"nine network",
"nine.network",
"nine_network",
"nine-network",
"nippon tv",
"nippon.tv",
"nippon_tv",
"nippon-tv",
"nitro",
"noa",
"noggin",
"nolife",
"noovo",
"northern visions television",
"northern.visions.television",
"northern_visions_television",
"northern-visions-television",
"nvt",
"nou 24",
"nou.24",
"nou_24",
"nou-24",
"n24",
"nou televisió",
"nou.televisió",
"nou_televisió",
"nou-televisió",
"nova",
"now tv",
"now.tv",
"now_tv",
"now-tv",
"nuevo siglo tv",
"nuevo.siglo.tv",
"nuevo_siglo_tv",
"nuevo-siglo-tv",
"nst",
"numéro 23",
"numéro.23",
"numéro_23",
"numéro-23",
"n23",
"obs gyeongin tv",
"obs.gyeongin.tv",
"obs_gyeongin_tv",
"obs-gyeongin-tv",
"ogt",
"ocn",
"ocs",
"oln",
"ondirectv (latin america)",
"ondirectv.(latin.america)",
"ondirectv_(latin_america)",
"ondirectv-(latin-america)",
"ola",
"orf 1",
"orf.1",
"orf_1",
"orf-1",
"orf 2",
"orf.2",
"orf_2",
"orf-2",
"orf iii",
"orf.iii",
"orf_iii",
"orf-iii",
"ortf",
"osn",
"ouftivi",
"own",
"oasis hd",
"oasis.hd",
"oasis_hd",
"oasis-hd",
"okoo",
"olive",
"omega tv",
"omega.tv",
"omega_tv",
"omega-tv",
"omni",
"omroep brabant",
"omroep.brabant",
"omroep_brabant",
"omroep-brabant",
"omroep max",
"omroep.max",
"omroep_max",
"omroep-max",
"onstyle",
"one 31",
"one.31",
"one_31",
"one-31",
"o31",
"one channel",
"one.channel",
"one_channel",
"one-channel",
"one magic",
"one.magic",
"one_magic",
"one-magic",
"open tv",
"open.tv",
"open_tv",
"open-tv",
"opto",
"ora tv",
"ora.tv",
"ora_tv",
"ora-tv",
"orange tv españa",
"orange.tv.españa",
"orange_tv_españa",
"orange-tv-españa",
"ote",
"ouatch",
"outtv",
"outdoor channel",
"outdoor.channel",
"outdoor_channel",
"outdoor-channel",
"ovation tv",
"ovation.tv",
"ovation_tv",
"ovation-tv",
"oxygen",
"pbs kids sprout",
"pbs.kids.sprout",
"pbs_kids_sprout",
"pbs-kids-sprout",
"pks",
"pbs",
"pptv",
"prima tv",
"prima.tv",
"prima_tv",
"prima-tv",
"pro tv",
"pro.tv",
"pro_tv",
"pro-tv",
"pts hd",
"pts.hd",
"pts_hd",
"pts-hd",
"pts taigi",
"pts.taigi",
"pts_taigi",
"pts-taigi",
"pts",
"ptv bolan",
"ptv.bolan",
"ptv_bolan",
"ptv-bolan",
"ptv global",
"ptv.global",
"ptv_global",
"ptv-global",
"ptv home",
"ptv.home",
"ptv_home",
"ptv-home",
"ptv news",
"ptv.news",
"ptv_news",
"ptv-news",
"pvc (uk)",
"pvc",
"pvc.(uk)",
"pvc_(uk)",
"pvc-(uk)",
"pakapaka",
"pantaya",
"paramount channel (fr)",
"paramount channel",
"paramountchannel",
"paramount.channel.(fr)",
"paramount_channel_(fr)",
"paramount-channel-(fr)",
"pcf",
"paramount comedy",
"paramount.comedy",
"paramount_comedy",
"paramount-comedy",
"paramount network",
"paramount.network",
"paramount_network",
"paramount-network",
"paramount+",
"paravi",
"paris première",
"paris.première",
"paris_première",
"paris-première",
"peacock",
"pcok",
"piccoma tv   ピッコマtv",
"piccoma.tv...ピッコマtv",
"piccoma_tv___ピッコマtv",
"piccoma-tv---ピッコマtv",
"pt  �",
"pick tv",
"pick.tv",
"pick_tv",
"pick-tv",
"pivot",
"planet green",
"planet.green",
"planet_green",
"planet-green",
"planète+",
"play more",
"play.more",
"play_more",
"play-more",
"play plus",
"play.plus",
"play_plus",
"play-plus",
"play uk",
"play.uk",
"play_uk",
"play-uk",
"playjam",
"playstation network",
"playstation.network",
"playstation_network",
"playstation-network",
"playboy tv",
"playboy.tv",
"playboy_tv",
"playboy-tv",
"playhouse disney france",
"playhouse.disney.france",
"playhouse_disney_france",
"playhouse-disney-france",
"pdf",
"playhouse disney",
"playhouse.disney",
"playhouse_disney",
"playhouse-disney",
"playz",
"plug rtl",
"plug.rtl",
"plug_rtl",
"plug-rtl",
"podcast (all platforms)",
"podcast.(all.platforms)",
"podcast_(all_platforms)",
"podcast-(all-platforms)",
"pap",
"polsat",
"polynésie 1ère",
"polynésie.1ère",
"polynésie_1ère",
"polynésie-1ère",
"p1�",
"pop tv",
"pop.tv",
"pop_tv",
"pop-tv",
"porto canal",
"porto.canal",
"porto_canal",
"porto-canal",
"powned",
"premier (russia)",
"premier",
"premier.(russia)",
"premier_(russia)",
"premier-(russia)",
"press tv",
"press.tv",
"press_tv",
"press-tv",
"prima televize",
"prima.televize",
"prima_televize",
"prima-televize",
"prime (be)",
"prime",
"prime.(be)",
"prime_(be)",
"prime-(be)",
"prime (nz)",
"prime.(nz)",
"prime_(nz)",
"prime-(nz)",
"prime box brazil",
"prime.box.brazil",
"prime_box_brazil",
"prime-box-brazil",
"pbb",
"prime video",
"prime.video",
"prime_video",
"prime-video",
"prosieben maxx",
"prosieben.maxx",
"prosieben_maxx",
"prosieben-maxx",
"prosieben",
"prva srpska televizija",
"prva.srpska.televizija",
"prva_srpska_televizija",
"prva-srpska-televizija",
"pst",
"pub channel",
"pub.channel",
"pub_channel",
"pub-channel",
"puls 4",
"puls.4",
"puls_4",
"puls-4",
"pureflix",
"pursuit channel",
"pursuit.channel",
"pursuit_channel",
"pursuit-channel",
"q tv",
"q.tv",
"q_tv",
"q-tv",
"qvc",
"qatar tv",
"qatar.tv",
"qatar_tv",
"qatar-tv",
"queens public television",
"queens.public.television",
"queens_public_television",
"queens-public-television",
"qpt",
"quest",
"quibi",
"r&r",
"rbb",
"rcn tv",
"rcn.tv",
"rcn_tv",
"rcn-tv",
"rcti",
"rctv",
"rdi",
"red+",
"rltv",
"rmc découverte",
"rmc.découverte",
"rmc_découverte",
"rmc-découverte",
"rmc sport",
"rmc.sport",
"rmc_sport",
"rmc-sport",
"rmc story",
"rmc.story",
"rmc_story",
"rmc-story",
"rtbf webcréation",
"rtbf.webcréation",
"rtbf_webcréation",
"rtbf-webcréation",
"rtbf",
"rtf télévision",
"rtf.télévision",
"rtf_télévision",
"rtf-télévision",
"rthk",
"rtl 4",
"rtl.4",
"rtl_4",
"rtl-4",
"rtl 5",
"rtl.5",
"rtl_5",
"rtl-5",
"rtl 7",
"rtl.7",
"rtl_7",
"rtl-7",
"rtl 8",
"rtl.8",
"rtl_8",
"rtl-8",
"rtl ii",
"rtl.ii",
"rtl_ii",
"rtl-ii",
"rtl klub",
"rtl.klub",
"rtl_klub",
"rtl-klub",
"rtl tvi",
"rtl.tvi",
"rtl_tvi",
"rtl-tvi",
"rtl television",
"rtl.television",
"rtl_television",
"rtl-television",
"rtl televizija",
"rtl.televizija",
"rtl_televizija",
"rtl-televizija",
"rtl xl",
"rtl.xl",
"rtl_xl",
"rtl-xl",
"rtl2",
"rtl9",
"rtl",
"rtlplus",
"rtp açores",
"rtp.açores",
"rtp_açores",
"rtp-açores",
"rtp madeira",
"rtp.madeira",
"rtp_madeira",
"rtp-madeira",
"rtp memória",
"rtp.memória",
"rtp_memória",
"rtp-memória",
"rtp play",
"rtp.play",
"rtp_play",
"rtp-play",
"rtp1",
"rtp2",
"rtp3",
"rts un",
"rts.un",
"rts_un",
"rts-un",
"rtv noord holland",
"rtv.noord.holland",
"rtv_noord_holland",
"rtv-noord-holland",
"rnh",
"rtvc spain",
"rtvc.spain",
"rtvc_spain",
"rtvc-spain",
"rtvs",
"rtvslo",
"rtÉ one",
"rtÉ.one",
"rtÉ_one",
"rtÉ-one",
"rtÉ two",
"rtÉ.two",
"rtÉ_two",
"rtÉ-two",
"rtÉjr",
"rvu",
"radio bremen",
"radio.bremen",
"radio_bremen",
"radio-bremen",
"radio television of serbia (rts/ptc)",
"radio television of serbia",
"radiotelevisionofserbia",
"radio.television.of.serbia.(rts/ptc)",
"radio_television_of_serbia_(rts/ptc)",
"radio-television-of-serbia-(rts/ptc)",
"rtosr",
"radio televizija vojvodine",
"radio.televizija.vojvodine",
"radio_televizija_vojvodine",
"radio-televizija-vojvodine",
"rtv",
"radio canada",
"radio.canada",
"radio_canada",
"radio-canada",
"radio québec",
"radio.québec",
"radio_québec",
"radio-québec",
"radiotopia",
"rai 1",
"rai.1",
"rai_1",
"rai-1",
"rai 2",
"rai.2",
"rai_2",
"rai-2",
"rai 3",
"rai.3",
"rai_3",
"rai-3",
"rai 4",
"rai.4",
"rai_4",
"rai-4",
"rai 5",
"rai.5",
"rai_5",
"rai-5",
"rai gulp",
"rai.gulp",
"rai_gulp",
"rai-gulp",
"raiplay",
"real time",
"real.time",
"real_time",
"real-time",
"really",
"record news",
"record.news",
"record_news",
"record-news",
"recordtv",
"red bull tv",
"red.bull.tv",
"red_bull_tv",
"red-bull-tv",
"rbt",
"red hot tv",
"red.hot.tv",
"red_hot_tv",
"red-hot-tv",
"rht",
"rede bandeirantes",
"rede.bandeirantes",
"rede_bandeirantes",
"rede-bandeirantes",
"rede brasil (rbtv)",
"rede brasil",
"redebrasil",
"rede.brasil.(rbtv)",
"rede_brasil_(rbtv)",
"rede-brasil-(rbtv)",
"rbr",
"rede globo",
"rede.globo",
"rede_globo",
"rede-globo",
"rede manchete",
"rede.manchete",
"rede_manchete",
"rede-manchete",
"rede vida",
"rede.vida",
"rede_vida",
"rede-vida",
"redetv!",
"reelzchannel",
"reshet 13",
"reshet.13",
"reshet_13",
"reshet-13",
"rete 4",
"rete.4",
"rete_4",
"rete-4",
"revelation tv",
"revelation.tv",
"revelation_tv",
"revelation-tv",
"revision3",
"revolt",
"rooster teeth",
"rooster.teeth",
"rooster_teeth",
"rooster-teeth",
"roya tv",
"roya.tv",
"roya_tv",
"roya-tv",
"royal news",
"royal.news",
"royal_news",
"royal-news",
"russia today",
"russia.today",
"russia_today",
"russia-today",
"russia 1",
"russia.1",
"russia_1",
"russia-1",
"ruutu",
"rÚv",
"s1tv",
"s4/c",
"s4c",
"sabc1",
"sabc2",
"sabc3",
"sapo vídeos",
"sapo.vídeos",
"sapo_vídeos",
"sapo-vídeos",
"sat 1",
"sat.1",
"sat_1",
"sat-1",
"sbs (au)",
"sbs",
"sbs.(au)",
"sbs_(au)",
"sbs-(au)",
"sbs (kr)",
"sbs.(kr)",
"sbs_(kr)",
"sbs-(kr)",
"sbs 6",
"sbs.6",
"sbs_6",
"sbs-6",
"sbs plus",
"sbs.plus",
"sbs_plus",
"sbs-plus",
"sbt",
"sec network",
"sec.network",
"sec_network",
"sec-network",
"set metro",
"set.metro",
"set_metro",
"set-metro",
"set tv",
"set.tv",
"set_tv",
"set-tv",
"sf 1",
"sf.1",
"sf_1",
"sf-1",
"sfr play",
"sfr.play",
"sfr_play",
"sfr-play",
"sic caras",
"sic.caras",
"sic_caras",
"sic-caras",
"sic comédia",
"sic.comédia",
"sic_comédia",
"sic-comédia",
"sic mulher",
"sic.mulher",
"sic_mulher",
"sic-mulher",
"sic notícias",
"sic.notícias",
"sic_notícias",
"sic-notícias",
"sic radical",
"sic.radical",
"sic_radical",
"sic-radical",
"sic",
"sky perfectv!",
"sky.perfectv!",
"sky_perfectv!",
"sky-perfectv!",
"soapnet",
"srf 1",
"srf.1",
"srf_1",
"srf-1",
"star chinese channel",
"star.chinese.channel",
"star_chinese_channel",
"star-chinese-channel",
"scc",
"star gold",
"star.gold",
"star_gold",
"star-gold",
"star movies",
"star.movies",
"star_movies",
"star-movies",
"star news",
"star.news",
"star_news",
"star-news",
"star one",
"star.one",
"star_one",
"star-one",
"star plus",
"star.plus",
"star_plus",
"star-plus",
"star sports asia",
"star.sports.asia",
"star_sports_asia",
"star-sports-asia",
"ssa",
"star sports hong kong",
"star.sports.hong.kong",
"star_sports_hong_kong",
"star-sports-hong-kong",
"sshk",
"star sports india",
"star.sports.india",
"star_sports_india",
"star-sports-india",
"ssi",
"star sports malaysia",
"star.sports.malaysia",
"star_sports_malaysia",
"star-sports-malaysia",
"ssm",
"star sports southeast asia",
"star.sports.southeast.asia",
"star_sports_southeast_asia",
"star-sports-southeast-asia",
"sssa",
"star sports taiwan",
"star.sports.taiwan",
"star_sports_taiwan",
"star-sports-taiwan",
"sst",
"star vijay",
"star.vijay",
"star_vijay",
"star-vijay",
"starz",
"stv (tw)",
"stv",
"stv.(tw)",
"stv_(tw)",
"stv-(tw)",
"stv (uk)",
"stv.(uk)",
"stv_(uk)",
"stv-(uk)",
"sun tv",
"sun.tv",
"sun_tv",
"sun-tv",
"sun music",
"sun.music",
"sun_music",
"sun-music",
"sun news",
"sun.news",
"sun_news",
"sun-news",
"svt 1",
"svt.1",
"svt_1",
"svt-1",
"svt 2",
"svt.2",
"svt_2",
"svt-2",
"svt24",
"svt",
"svtb",
"swr",
"syfy",
"sab tv",
"sab.tv",
"sab_tv",
"sab-tv",
"sahara one",
"sahara.one",
"sahara_one",
"sahara-one",
"salto",
"sama dubai tv",
"sama.dubai.tv",
"sama_dubai_tv",
"sama-dubai-tv",
"sdt",
"sama tv",
"sama.tv",
"sama_tv",
"sama-tv",
"sanskar",
"science channel",
"science.channel",
"science_channel",
"science-channel",
"scuzz",
"seeso",
"seezn",
"semerkand tv",
"semerkand.tv",
"semerkand_tv",
"semerkand-tv",
"servus tv",
"servus.tv",
"servus_tv",
"servus-tv",
"sesctv",
"setanta ireland",
"setanta.ireland",
"setanta_ireland",
"setanta-ireland",
"seven network",
"seven.network",
"seven_network",
"seven-network",
"señal colombia",
"señal.colombia",
"señal_colombia",
"señal-colombia",
"shahid (uae)",
"shahid",
"shahid.(uae)",
"shahid_(uae)",
"shahid-(uae)",
"shandong television",
"shandong.television",
"shandong_television",
"shandong-television",
"shenzhen tv",
"shenzhen.tv",
"shenzhen_tv",
"shenzhen-tv",
"shout! factory (usa)",
"shout! factory",
"shout!factory",
"shout!.factory.(usa)",
"shout!_factory_(usa)",
"shout!-factory-(usa)",
"sfu",
"show tv",
"show.tv",
"show_tv",
"show-tv",
"showmax poland",
"showmax.poland",
"showmax_poland",
"showmax-poland",
"showmax",
"showcase (au)",
"showcase",
"showcase.(au)",
"showcase_(au)",
"showcase-(au)",
"showtime",
"shudder",
"sigma tv",
"sigma.tv",
"sigma_tv",
"sigma-tv",
"sirasa",
"sixx",
"sjónvarp símans",
"sjónvarp.símans",
"sjónvarp_símans",
"sjónvarp-símans",
"skai",
"sky arte",
"sky.arte",
"sky_arte",
"sky-arte",
"sky arts",
"sky.arts",
"sky_arts",
"sky-arts",
"sky atlantic (de)",
"sky atlantic",
"skyatlantic",
"sky.atlantic.(de)",
"sky_atlantic_(de)",
"sky-atlantic-(de)",
"sad",
"sky atlantic (it)",
"sky.atlantic.(it)",
"sky_atlantic_(it)",
"sky-atlantic-(it)",
"sai",
"sky atlantic (uk)",
"sky.atlantic.(uk)",
"sky_atlantic_(uk)",
"sky-atlantic-(uk)",
"sau",
"sky box office",
"sky.box.office",
"sky_box_office",
"sky-box-office",
"sbo",
"sky cinema (it)",
"sky cinema",
"skycinema",
"sky.cinema.(it)",
"sky_cinema_(it)",
"sky-cinema-(it)",
"sci",
"sky cinema (uk)",
"sky.cinema.(uk)",
"sky_cinema_(uk)",
"sky-cinema-(uk)",
"scu",
"sky comedy",
"sky.comedy",
"sky_comedy",
"sky-comedy",
"sky crime (uk)",
"sky crime",
"skycrime",
"sky.crime.(uk)",
"sky_crime_(uk)",
"sky-crime-(uk)",
"sky deutschland",
"sky.deutschland",
"sky_deutschland",
"sky-deutschland",
"sky documentaries",
"sky.documentaries",
"sky_documentaries",
"sky-documentaries",
"sky kids",
"sky.kids",
"sky_kids",
"sky-kids",
"sky living",
"sky.living",
"sky_living",
"sky-living",
"sky movies",
"sky.movies",
"sky_movies",
"sky-movies",
"sky nature",
"sky.nature",
"sky_nature",
"sky-nature",
"sky news ireland",
"sky.news.ireland",
"sky_news_ireland",
"sky-news-ireland",
"sni",
"sky news",
"sky.news",
"sky_news",
"sky-news",
"sky one (de)",
"sky one",
"skyone",
"sky.one.(de)",
"sky_one_(de)",
"sky-one-(de)",
"sod",
"sky.one",
"sky_one",
"sky-one",
"sky sports f1",
"sky.sports.f1",
"sky_sports_f1",
"sky-sports-f1",
"ssf",
"skysportsf1",
"sky sports",
"sky.sports",
"sky_sports",
"sky-sports",
"sky travel",
"sky.travel",
"sky_travel",
"sky-travel",
"sky uno",
"sky.uno",
"sky_uno",
"sky-uno",
"sky witness",
"sky.witness",
"sky_witness",
"sky-witness",
"sky2",
"sky3",
"slice",
"smash hits",
"smash.hits",
"smash_hits",
"smash-hits",
"smithsonian channel (ca)",
"smithsonian channel",
"smithsonianchannel",
"smithsonian.channel.(ca)",
"smithsonian_channel_(ca)",
"smithsonian-channel-(ca)",
"smithsonian.channel",
"smithsonian_channel",
"smithsonian-channel",
"snapchat originals",
"snapchat.originals",
"snapchat_originals",
"snapchat-originals",
"soho",
"sohu tv",
"sohu.tv",
"sohu_tv",
"sohu-tv",
"sony channel",
"sony.channel",
"sony_channel",
"sony-channel",
"sony entertainment television",
"sony.entertainment.television",
"sony_entertainment_television",
"sony-entertainment-television",
"set",
"sonyliv",
"space (brasil)",
"space",
"space.(brasil)",
"space_(brasil)",
"space-(brasil)",
"space (latin america)",
"space.(latin.america)",
"space_(latin_america)",
"space-(latin-america)",
"sla",
"spectrum",
"speed",
"spektrum",
"spike (nl)",
"spike",
"spike.(nl)",
"spike_(nl)",
"spike-(nl)",
"spike tv",
"spike.tv",
"spike_tv",
"spike-tv",
"sportv",
"sportsman channel",
"sportsman.channel",
"sportsman_channel",
"sportsman-channel",
"sportsnet",
"stan",
"star (latin america)",
"star.(latin.america)",
"star_(latin_america)",
"star-(latin-america)",
"star bharat",
"star.bharat",
"star_bharat",
"star-bharat",
"star channel (br)",
"star channel",
"starchannel",
"star.channel.(br)",
"star_channel_(br)",
"star-channel-(br)",
"scb",
"star channel (greece)",
"star.channel.(greece)",
"star_channel_(greece)",
"star-channel-(greece)",
"scg",
"star comedy",
"star.comedy",
"star_comedy",
"star-comedy",
"star hits 1 (brazil)",
"star hits 1",
"starhits1",
"star.hits.1.(brazil)",
"star_hits_1_(brazil)",
"star-hits-1-(brazil)",
"sh1 b",
"star hits 2 (brazil)",
"star hits 2",
"starhits2",
"star.hits.2.(brazil)",
"star_hits_2_(brazil)",
"star-hits-2-(brazil)",
"sh2 b",
"star jalsha",
"star.jalsha",
"star_jalsha",
"star-jalsha",
"star life (br)",
"star life",
"starlife",
"star.life.(br)",
"star_life_(br)",
"star-life-(br)",
"slb",
"star life (latin america)",
"star.life.(latin.america)",
"star_life_(latin_america)",
"star-life-(latin-america)",
"slla",
"star media",
"star.media",
"star_media",
"star-media",
"star tv",
"star.tv",
"star_tv",
"star-tv",
"star world",
"star.world",
"star_world",
"star-world",
"stargate command",
"stargate.command",
"stargate_command",
"stargate-command",
"start russia",
"start.russia",
"start_russia",
"start-russia",
"steel",
"streamz",
"studio 100 tv",
"studio.100.tv",
"studio_100_tv",
"studio-100-tv",
"s100 t",
"studio 23",
"studio.23",
"studio_23",
"studio-23",
"s23",
"studio 4",
"studio.4",
"studio_4",
"studio-4",
"studio+",
"style",
"stöð 2",
"stöð.2",
"stöð_2",
"stöð-2",
"sub",
"sun television",
"sun.television",
"sun_television",
"sun-television",
"sundance tv",
"sundance.tv",
"sundance_tv",
"sundance-tv",
"sundancetv",
"suoimitv",
"super channel",
"super.channel",
"super_channel",
"super-channel",
"super rtl",
"super.rtl",
"super_rtl",
"super-rtl",
"super Écran",
"super.Écran",
"super_Écran",
"super-Écran",
"super!",
"superstar tv",
"superstar.tv",
"superstar_tv",
"superstar-tv",
"superstation wgn",
"superstation.wgn",
"superstation_wgn",
"superstation-wgn",
"swarnawahini",
"swearnet",
"syndication",
"syrian drama tv",
"syrian.drama.tv",
"syrian_drama_tv",
"syrian-drama-tv",
"séries+",
"tbd",
"tbn (trinity broadcasting network)",
"tbn.(trinity.broadcasting.network)",
"tbn_(trinity_broadcasting_network)",
"tbn-(trinity-broadcasting-network)",
"ttbn",
"tbs (latin america)",
"tbs.(latin.america)",
"tbs_(latin_america)",
"tbs-(latin-america)",
"tla",
"tbs",
"tcm",
"teenick",
"ten spain",
"ten.spain",
"ten_spain",
"ten-spain",
"ten sports",
"ten.sports",
"ten_sports",
"ten-sports",
"tet",
"tf1 séries films",
"tf1.séries.films",
"tf1_séries_films",
"tf1-séries-films",
"tsf",
"tf1",
"tfo",
"tfx",
"tg4",
"tgrt haber",
"tgrt.haber",
"tgrt_haber",
"tgrt-haber",
"timvision",
"titv",
"tlc india",
"tlc.india",
"tlc_india",
"tlc-india",
"tlc",
"tmc",
"tmf",
"tnt  (russia)",
"tnt ",
"tntsports",
"tnt",
"tnt..(russia)",
"tnt__(russia)",
"tnt--(russia)",
"tnt (us)",
"tnt.(us)",
"tnt_(us)",
"tnt-(us)",
"tnt brasil",
"tnt.brasil",
"tnt_brasil",
"tnt-brasil",
"tnt comedy (germany)",
"tnt comedy",
"tntcomedy",
"tnt.comedy.(germany)",
"tnt_comedy_(germany)",
"tnt-comedy-(germany)",
"tcg",
"tnt latin america",
"tnt.latin.america",
"tnt_latin_america",
"tnt-latin-america",
"tnt serie",
"tnt.serie",
"tnt_serie",
"tnt-serie",
"tnt spain",
"tnt.spain",
"tnt_spain",
"tnt-spain",
"tnu",
"tonton",
"tqs",
"trk ukraina",
"trk.ukraina",
"trk_ukraina",
"trk-ukraina",
"tros",
"trt 1",
"trt.1",
"trt_1",
"trt-1",
"trt arabic",
"trt.arabic",
"trt_arabic",
"trt-arabic",
"trt avaz",
"trt.avaz",
"trt_avaz",
"trt-avaz",
"trt belgesel",
"trt.belgesel",
"trt_belgesel",
"trt-belgesel",
"trt diyanet",
"trt.diyanet",
"trt_diyanet",
"trt-diyanet",
"trt hd",
"trt.hd",
"trt_hd",
"trt-hd",
"trt haber",
"trt.haber",
"trt_haber",
"trt-haber",
"trt kurdî",
"trt.kurdî",
"trt_kurdî",
"trt-kurdî",
"trt okul",
"trt.okul",
"trt_okul",
"trt-okul",
"trt türk",
"trt.türk",
"trt_türk",
"trt-türk",
"trt world",
"trt.world",
"trt_world",
"trt-world",
"trt Çocuk",
"trt.Çocuk",
"trt_Çocuk",
"trt-Çocuk",
"tsn",
"tsr",
"ttv (pl)",
"ttv",
"ttv.(pl)",
"ttv_(pl)",
"ttv-(pl)",
"tv 2 (dk)",
"tv 2",
"tv2",
"tv.2.(dk)",
"tv_2_(dk)",
"tv-2-(dk)",
"t2 d",
"tv 2 charlie",
"tv.2.charlie",
"tv_2_charlie",
"tv-2-charlie",
"t2 c",
"tv 2 fri",
"tv.2.fri",
"tv_2_fri",
"tv-2-fri",
"t2 f",
"tv 2 sport",
"tv.2.sport",
"tv_2_sport",
"tv-2-sport",
"t2 s",
"tv 2 sumo",
"tv.2.sumo",
"tv_2_sumo",
"tv-2-sumo",
"tv 2 zebra",
"tv.2.zebra",
"tv_2_zebra",
"tv-2-zebra",
"t2 z",
"tv 2 zulu",
"tv.2.zulu",
"tv_2_zulu",
"tv-2-zulu",
"tv 2/nord",
"tv.2/nord",
"tv_2/nord",
"tv-2/nord",
"t2/",
"tv.2",
"tv_2",
"tv-2",
"tv 3",
"tv.3",
"tv_3",
"tv-3",
"tv 4",
"tv.4",
"tv_4",
"tv-4",
"tv aichi",
"tv.aichi",
"tv_aichi",
"tv-aichi",
"tv aparecida",
"tv.aparecida",
"tv_aparecida",
"tv-aparecida",
"tv asahi",
"tv.asahi",
"tv_asahi",
"tv-asahi",
"tv azteca",
"tv.azteca",
"tv_azteca",
"tv-azteca",
"tv brasil",
"tv.brasil",
"tv_brasil",
"tv-brasil",
"tv chile",
"tv.chile",
"tv_chile",
"tv-chile",
"tv cultura",
"tv.cultura",
"tv_cultura",
"tv-cultura",
"tv joj",
"tv.joj",
"tv_joj",
"tv-joj",
"tv land",
"tv.land",
"tv_land",
"tv-land",
"tv markíza",
"tv.markíza",
"tv_markíza",
"tv-markíza",
"tv net",
"tv.net",
"tv_net",
"tv-net",
"tv nova",
"tv.nova",
"tv_nova",
"tv-nova",
"tv okey",
"tv.okey",
"tv_okey",
"tv-okey",
"tv one (nz)",
"tv one",
"tvone",
"tv.one.(nz)",
"tv_one_(nz)",
"tv-one-(nz)",
"ton",
"tv.one",
"tv_one",
"tv-one",
"tv osaka",
"tv.osaka",
"tv_osaka",
"tv-osaka",
"tv perú",
"tv.perú",
"tv_perú",
"tv-perú",
"tv pública",
"tv.pública",
"tv_pública",
"tv-pública",
"tv são carlos",
"tv.são.carlos",
"tv_são_carlos",
"tv-são-carlos",
"tsc",
"tv thunder",
"tv.thunder",
"tv_thunder",
"tv-thunder",
"tv tokyo",
"tv.tokyo",
"tv_tokyo",
"tv-tokyo",
"tv tupi",
"tv.tupi",
"tv_tupi",
"tv-tupi",
"tv 3 (russia)",
"tv3",
"tv.3.(russia)",
"tv_3_(russia)",
"tv-3-(russia)",
"t3 r",
"tv1 (my)",
"tv1",
"tv1.(my)",
"tv1_(my)",
"tv1-(my)",
"tv11",
"tv2 (my)",
"tv2.(my)",
"tv2_(my)",
"tv2-(my)",
"tv24 (ch)",
"tv24",
"tv24.(ch)",
"tv24_(ch)",
"tv24-(ch)",
"tv25 (ch)",
"tv25",
"tv25.(ch)",
"tv25_(ch)",
"tv25-(ch)",
"tv3 (es)",
"tv3.(es)",
"tv3_(es)",
"tv3-(es)",
"tv3 (ie)",
"tv3.(ie)",
"tv3_(ie)",
"tv3-(ie)",
"tv3 (my)",
"tv3.(my)",
"tv3_(my)",
"tv3-(my)",
"tv3 (no)",
"tv3.(no)",
"tv3_(no)",
"tv3-(no)",
"tv3 (nz) three",
"tv3.(nz).three",
"tv3_(nz)_three",
"tv3-(nz)-three",
"tv3 (se)",
"tv3.(se)",
"tv3_(se)",
"tv3-(se)",
"tv3 puls",
"tv3.puls",
"tv3_puls",
"tv3-puls",
"tv3+",
"tv4 (nz)",
"tv4",
"tv4.(nz)",
"tv4_(nz)",
"tv4-(nz)",
"tv4 fakta",
"tv4.fakta",
"tv4_fakta",
"tv4-fakta",
"tv4 guld",
"tv4.guld",
"tv4_guld",
"tv4-guld",
"tv4 komedi",
"tv4.komedi",
"tv4_komedi",
"tv4-komedi",
"tv4 plus",
"tv4.plus",
"tv4_plus",
"tv4-plus",
"tv4 science fiction",
"tv4.science.fiction",
"tv4_science_fiction",
"tv4-science-fiction",
"tv5 (ca)",
"tv5",
"tv5.(ca)",
"tv5_(ca)",
"tv5-(ca)",
"tv5 (fi)",
"tv5.(fi)",
"tv5_(fi)",
"tv5-(fi)",
"tv5 (ph)",
"tv5.(ph)",
"tv5_(ph)",
"tv5-(ph)",
"tv5 monde",
"tv5.monde",
"tv5_monde",
"tv5-monde",
"tv6",
"tv7 (bg)",
"tv7",
"tv7.(bg)",
"tv7_(bg)",
"tv7-(bg)",
"tv7 (se)",
"tv7.(se)",
"tv7_(se)",
"tv7-(se)",
"tv8 (it)",
"tv8",
"tv8.(it)",
"tv8_(it)",
"tv8-(it)",
"tv8 (se)",
"tv8.(se)",
"tv8_(se)",
"tv8-(se)",
"tv8 (tr)",
"tv8.(tr)",
"tv8_(tr)",
"tv8-(tr)",
"tv9",
"tva (jp)",
"tva",
"tva.(jp)",
"tva_(jp)",
"tva-(jp)",
"tvb",
"tvbs entertainment channel",
"tvbs.entertainment.channel",
"tvbs_entertainment_channel",
"tvbs-entertainment-channel",
"tec",
"tvbs",
"tve",
"tvfplay",
"tvg network",
"tvg.network",
"tvg_network",
"tvg-network",
"tvgn",
"tvi24",
"tvi",
"tving",
"tvm",
"tvn style",
"tvn.style",
"tvn_style",
"tvn-style",
"tvn turbo",
"tvn.turbo",
"tvn_turbo",
"tvn-turbo",
"tvn",
"tvnow",
"tvnz 1",
"tvnz.1",
"tvnz_1",
"tvnz-1",
"tvnz 2",
"tvnz.2",
"tvnz_2",
"tvnz-2",
"tvnz",
"tvnorge",
"tvo",
"tvone global",
"tvone.global",
"tvone_global",
"tvone-global",
"tvp sa",
"tvp.sa",
"tvp_sa",
"tvp-sa",
"tvp1",
"tvp2",
"tvq (australia)",
"tvq",
"tvq.(australia)",
"tvq_(australia)",
"tvq-(australia)",
"tvq (japan)",
"tvq.(japan)",
"tvq_(japan)",
"tvq-(japan)",
"tvr 2",
"tvr.2",
"tvr_2",
"tvr-2",
"tvri",
"tvs china",
"tvs.china",
"tvs_china",
"tvs-china",
"tvs sydney",
"tvs.sydney",
"tvs_sydney",
"tvs-sydney",
"tvsa",
"twit",
"txn (japan)",
"txn",
"txn.(japan)",
"txn_(japan)",
"txn-(japan)",
"tyt network",
"tyt.network",
"tyt_network",
"tyt-network",
"tele 5",
"tele.5",
"tele_5",
"tele-5",
"teleg",
"telezüri",
"telecinco",
"teledoce",
"telefe",
"telefuturo",
"telelatino",
"telemundo",
"teletama",
"teletoon",
"televen",
"televisa",
"television maldives",
"television.maldives",
"television_maldives",
"television-maldives",
"television osaka",
"television.osaka",
"television_osaka",
"television-osaka",
"televisión de galicia",
"televisión.de.galicia",
"televisión_de_galicia",
"televisión-de-galicia",
"tdg",
"tencent video",
"tencent.video",
"tencent_video",
"tencent-video",
"terra viva",
"terra.viva",
"terra_viva",
"terra-viva",
"testtube",
"tevéciudad",
"thames television",
"thames.television",
"thames_television",
"thames-television",
"the 5 network",
"the.5.network",
"the_5_network",
"the-5-network",
"t5 n",
"the africa channel (uk)",
"the africa channel",
"theafricachannel",
"the.africa.channel.(uk)",
"the_africa_channel_(uk)",
"the-africa-channel-(uk)",
"tacu",
"the africa channel (us)",
"the.africa.channel.(us)",
"the_africa_channel_(us)",
"the-africa-channel-(us)",
"the amp",
"the.amp",
"the_amp",
"the-amp",
"the box",
"the.box",
"the_box",
"the-box",
"the brewdog network",
"the.brewdog.network",
"the_brewdog_network",
"the-brewdog-network",
"tbn",
"the cw",
"the.cw",
"the_cw",
"the-cw",
"the comedy channel",
"the.comedy.channel",
"the_comedy_channel",
"the-comedy-channel",
"tcc",
"the den",
"the.den",
"the_den",
"the-den",
"the family channel",
"the.family.channel",
"the_family_channel",
"the-family-channel",
"tfc",
"the great courses",
"the.great.courses",
"the_great_courses",
"the-great-courses",
"tgc",
"the hub",
"the.hub",
"the_hub",
"the-hub",
"the movie network",
"the.movie.network",
"the_movie_network",
"the-movie-network",
"tmn",
"the nashville network",
"the.nashville.network",
"the_nashville_network",
"the-nashville-network",
"tnn",
"the national network",
"the.national.network",
"the_national_network",
"the-national-network",
"the roku channel",
"the.roku.channel",
"the_roku_channel",
"the-roku-channel",
"trc",
"the sportsman channel",
"the.sportsman.channel",
"the_sportsman_channel",
"the-sportsman-channel",
"the verge",
"the.verge",
"the_verge",
"the-verge",
"the wb",
"the.wb",
"the_wb",
"the-wb",
"the weather channel",
"the.weather.channel",
"the_weather_channel",
"the-weather-channel",
"twc",
"the zeus network",
"the.zeus.network",
"the_zeus_network",
"the-zeus-network",
"tzn",
"theblaze",
"this tv",
"this.tv",
"this_tv",
"this-tv",
"tik tok",
"tik.tok",
"tik_tok",
"tik-tok",
"tiktok",
"tipik",
"toei channel",
"toei.channel",
"toei_channel",
"toei-channel",
"toggle",
"tokai tv",
"tokai.tv",
"tokai_tv",
"tokai-tv",
"tokyo broadcasting system",
"tokyo.broadcasting.system",
"tokyo_broadcasting_system",
"tokyo-broadcasting-system",
"tokyo mx",
"tokyo.mx",
"tokyo_mx",
"tokyo-mx",
"tongyang broadcasting company",
"tongyang.broadcasting.company",
"tongyang_broadcasting_company",
"tongyang-broadcasting-company",
"tbc",
"toon disney",
"toon.disney",
"toon_disney",
"toon-disney",
"tou tv",
"tou.tv",
"tou_tv",
"tou-tv",
"toute l'histoire",
"toute.l'histoire",
"toute_l'histoire",
"toute-l'histoire",
"travel + escape",
"travel.+.escape",
"travel_+_escape",
"travel-+-escape",
"t+e",
"travel channel (uk)",
"travel channel",
"travelchannel",
"travel.channel.(uk)",
"travel_channel_(uk)",
"travel-channel-(uk)",
"tcu",
"travel.channel",
"travel_channel",
"travel-channel",
"treehouse tv",
"treehouse.tv",
"treehouse_tv",
"treehouse-tv",
"trend e",
"trend.e",
"trend_e",
"trend-e",
"trueid",
"truevisions",
"tubi",
"turner south",
"turner.south",
"turner_south",
"turner-south",
"twitch",
"twitter",
"télé québec",
"télé.québec",
"télé_québec",
"télé-québec",
"télétoon",
"ufc fight pass",
"ufc.fight.pass",
"ufc_fight_pass",
"ufc-fight-pass",
"ufp",
"uk entertainment channel",
"uk.entertainment.channel",
"uk_entertainment_channel",
"uk-entertainment-channel",
"uec",
"uktv drama",
"uktv.drama",
"uktv_drama",
"uktv-drama",
"uktv food",
"uktv.food",
"uktv_food",
"uktv-food",
"uktv gold",
"uktv.gold",
"uktv_gold",
"uktv-gold",
"uktv history",
"uktv.history",
"uktv_history",
"uktv-history",
"uktv style",
"uktv.style",
"uktv_style",
"uktv-style",
"uktv yesterday",
"uktv.yesterday",
"uktv_yesterday",
"uktv-yesterday",
"umc",
"un3tv",
"untv 37",
"untv.37",
"untv_37",
"untv-37",
"u37",
"upn",
"uptv",
"usa network",
"usa.network",
"usa_network",
"usa-network",
"utv",
"unis tv",
"unis.tv",
"unis_tv",
"unis-tv",
"united nations television",
"united.nations.television",
"united_nations_television",
"united-nations-television",
"unt",
"univer video",
"univer.video",
"univer_video",
"univer-video",
"universal kids",
"universal.kids",
"universal_kids",
"universal-kids",
"universal tv",
"universal.tv",
"universal_tv",
"universal-tv",
"universo",
"univision",
"urban america television",
"urban.america.television",
"urban_america_television",
"urban-america-television",
"uat",
"urbanflix",
"urdu 1",
"urdu.1",
"urdu_1",
"urdu-1",
"ustream",
"v télé",
"v.télé",
"v_télé",
"v-télé",
"vara",
"venn",
"vh1 brasil",
"vh1.brasil",
"vh1_brasil",
"vh1-brasil",
"vh1",
"vier",
"vijf",
"vlive",
"vox",
"vpro",
"vrt",
"vrv",
"vt4",
"vtm",
"vvvvid",
"varsity tv",
"varsity.tv",
"varsity_tv",
"varsity-tv",
"velocity",
"venevision",
"veronica",
"versus",
"veteran television",
"veteran.television",
"veteran_television",
"veteran-television",
"viafree",
"viaplay",
"viasat 4",
"viasat.4",
"viasat_4",
"viasat-4",
"viasat3",
"vice on tv (us)",
"vice on tv",
"viceontv",
"vice.on.tv.(us)",
"vice_on_tv_(us)",
"vice-on-tv-(us)",
"votu",
"viceland (ca)",
"viceland",
"viceland.(ca)",
"viceland_(ca)",
"viceland-(ca)",
"viceland (fr)",
"viceland.(fr)",
"viceland_(fr)",
"viceland-(fr)",
"viceland (nl)",
"viceland.(nl)",
"viceland_(nl)",
"viceland-(nl)",
"viceland (uk)",
"viceland.(uk)",
"viceland_(uk)",
"viceland-(uk)",
"vidangel (usa)",
"vidangel",
"vidangel.(usa)",
"vidangel_(usa)",
"vidangel-(usa)",
"videoland (nl)",
"videoland",
"videoland.(nl)",
"videoland_(nl)",
"videoland-(nl)",
"videoland television network",
"videoland.television.network",
"videoland_television_network",
"videoland-television-network",
"vtn",
"vidi space",
"vidi.space",
"vidi_space",
"vidi-space",
"vidol",
"vijftv",
"viki",
"vimeo",
"virgin media one",
"virgin.media.one",
"virgin_media_one",
"virgin-media-one",
"vmo",
"viutv",
"viva",
"volksmusik tv",
"volksmusik.tv",
"volksmusik_tv",
"volksmusik-tv",
"voot",
"voyage",
"vrak tv",
"vrak.tv",
"vrak_tv",
"vrak-tv",
"vudu",
"w network",
"w.network",
"w_network",
"w-network",
"wcny",
"wdr",
"we tv",
"we.tv",
"we_tv",
"we-tv",
"wgn america",
"wgn.america",
"wgn_america",
"wgn-america",
"wnl",
"wow presents plus",
"wow.presents.plus",
"wow_presents_plus",
"wow-presents-plus",
"wpp",
"wowow",
"wpix",
"wwe network",
"wwe.network",
"wwe_network",
"wwe-network",
"warner channel",
"warner.channel",
"warner_channel",
"warner-channel",
"warner tv",
"warner.tv",
"warner_tv",
"warner-tv",
"watchfrance",
"wavve",
"wealthtv",
"weverse (kr)",
"weverse",
"weverse.(kr)",
"weverse_(kr)",
"weverse-(kr)",
"workpoint tv",
"workpoint.tv",
"workpoint_tv",
"workpoint-tv",
"xy tv",
"xy.tv",
"xy_tv",
"xy-tv",
"xbox video",
"xbox.video",
"xbox_video",
"xbox-video",
"xee",
"xtvn",
"yahoo! view",
"yahoo!.view",
"yahoo!_view",
"yahoo!-view",
"yle",
"ytv (jp)",
"ytv",
"ytv.(jp)",
"ytv_(jp)",
"ytv-(jp)",
"ytv (uk)",
"ytv.(uk)",
"ytv_(uk)",
"ytv-(uk)",
"yahoo! screen",
"yahoo!.screen",
"yahoo!_screen",
"yahoo!-screen",
"youtube premium",
"youtube.premium",
"youtube_premium",
"youtube-premium",
"youtube",
"youku",
"zdf kultur",
"zdf.kultur",
"zdf_kultur",
"zdf-kultur",
"zdf",
"zdfinfo",
"zdfneo",
"zoom",
"ztv",
"zee cinema",
"zee.cinema",
"zee_cinema",
"zee-cinema",
"zee gujarati",
"zee.gujarati",
"zee_gujarati",
"zee-gujarati",
"zee muzic",
"zee.muzic",
"zee_muzic",
"zee-muzic",
"zee tv",
"zee.tv",
"zee_tv",
"zee-tv",
"zee5",
"zeste",
"zhejiang tv",
"zhejiang.tv",
"zhejiang_tv",
"zhejiang-tv",
"addiktv",
"btv",
"bein connect",
"bein.connect",
"bein_connect",
"bein-connect",
"dk4",
"documentary channel",
"documentary.channel",
"documentary_channel",
"documentary-channel",
"element14",
"eqhd",
"france tv slash",
"france.tv.slash",
"france_tv_slash",
"france-tv-slash",
"fts",
"france tv",
"france.tv",
"france_tv",
"france-tv",
"fridayvideo",
"here!",
"hulu japan",
"hulu.japan",
"hulu_japan",
"hulu-japan",
"iqiyi",
"iwanttfc",
"ivi (russia)",
"ivi",
"ivi.(russia)",
"ivi_(russia)",
"ivi-(russia)",
"jtbc",
"motorsports tv",
"motorsports.tv",
"motorsports_tv",
"motorsports-tv",
"myvideo",
"n tv",
"n.tv",
"n_tv",
"n-tv",
"oksusu",
"puhutv",
"radx",
"revry",
"rmusic tv",
"rmusic.tv",
"rmusic_tv",
"rmusic-tv",
"serieclub",
"trutv",
"tvk",
"téva",
"vtm be",
"vtm.be",
"vtm_be",
"vtm-be",
"vtmkzoom",
"yes",
"À punt",
"À.punt",
"À_punt",
"À-punt",
"Évasion",
"Ülke tv",
"Ülke.tv",
"Ülke_tv",
"Ülke-tv",
"één",
"Československá televize",
"Československá.televize",
"Československá_televize",
"Československá-televize",
"Česká televize",
"Česká.televize",
"Česká_televize",
"Česká-televize",
"Інтер",
"ДТВ",
"Дождь",
"Домашний",
"Звезда",
"Мульт",
"НТВ",
"Пятый канал",
"Пятый.канал",
"Пятый_канал",
"Пятый-канал",
"РЕН",
"Россия К",
"Россия.К",
"Россия_К",
"Россия-К",
"СТБ",
"СТС",
"ТВ Центр",
"ТВ.Центр",
"ТВ_Центр",
"ТВ-Центр",
"ТВС",
"הערוץ הראשון",
"הערוץ.הראשון",
"הערוץ_הראשון",
"הערוץ-הראשון",
"טלעד",
"ערוץ 10",
"ערוץ.10",
"ערוץ_10",
"ערוץ-10",
"�10",
"ערוץ הילדים‎",
"ערוץ.הילדים‎",
"ערוץ_הילדים‎",
"ערוץ-הילדים‎",
"רשת",
]